### ISSUE TITLE
Issue.java:32-34: Implement Comments::Issue.comments()....

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#100]
The puzzle `97-bcc117e9` from #97 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/fdbd1d044d9248d08980205b75dd71cc9e86f974/self-api/src/main/java/com/selfxdsd/api/Issue.java#L32-L34

The puzzle was created by @amihaiemil on 24-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this

**Comment by amihaiemil** [comment]
@criske sure, go ahead (listing comments should happen via the iterator() method; i.e. interface Comments extends Iterable<Comment>)

**Comment by amihaiemil** [comment]
paid with transaction id 57492179F0155882Y
