### ISSUE TITLE
StripeWallet.java: Method remove() in this class... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#1009]
The puzzle ``-36780584`` originating from #1004 has to be resolved:

https://github.com/self-xdsd/self-core/blob/c94f008abe24c1cc5691b266c485e7b1e5004a0d/self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java#L53-L54

"Method remove() in this class should remove the wallet (Customer) from Stripe before removing it from our Storage.".

The puzzle was created by @amihaiemil at ``2021-02-22 11:28:28 +0200``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-04T11:37:17.183071``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike add

**Comment by charlesmike** [comment]
> @charlesmike add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by amihaiemil** [comment]
@andreoss I'll take care of this one. I'm the only one who has access to the Stripe Dashboard to verify that it works.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-04T11:47:17.347171``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
