### ISSUE TITLE
GithubIssues.java:37-40: Implement and unit test method...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#101]
The puzzle `97-8b9168b0` from #97 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/fdbd1d044d9248d08980205b75dd71cc9e86f974/self-core-impl/src/main/java/com/selfxdsd/core/issues/GithubIssues.java#L37-L40

The puzzle was created by @amihaiemil on 24-May-20. 

 role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
Sign me up

**Comment by amihaiemil** [comment]
paid with transaction id: 6EV87513ED468354G

**Comment by 0pdd** [comment]
The puzzle `97-8b9168b0` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
