### ISSUE TITLE
Remove FakeWallet on Real Wallet activation

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1030]
When we activate a real Wallet, we should remove the Fake wallet.

First step is to add method Wallet.acitvate(). In the case of a real wallet, after calling this.storage.wallets().activate(this), the method should iterate over the project's wallets and remove the fake wallet if it exists.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-14T18:40:40.088294``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
