### ISSUE TITLE
BitbucketWebhooks.java: Continue writing tests for Bi... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1052]
The puzzle ``1594906508`` originating from #1015 has to be resolved:

https://github.com/self-xdsd/self-core/blob/36dbcb49c816783d5c692f5ef004812a70240ccf/self-core-impl/src/main/java/com/selfxdsd/core/BitbucketWebhooks.java#L50-L50

"Continue writing tests for BitbucketWebhooks class.".

The puzzle was created by @fellahi-ali at ``2021-03-10 10:36:02 +0100``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-20T11:07:17.731533``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-03-20T11:07:18). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@amihaiemil Looks like you've missed the task deadline (2021-03-20T11:07:18). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by zoeself** [comment]
@nmonokov this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-30T13:27:21.653779``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-30T14:07:17.694192``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske Don't forget to close this ticket before the deadline (2021-03-30T14:07:18). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
