### ISSUE TITLE
Implement The "commands" Command

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1071]
We should implement the ``commands`` command. When the user says ``@zoeself commands``, the PM should reply with the commands which it can support, their keywords and explanation.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-11T15:10:55.613900``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske do you still remember this area of the code? :D 

If yes, please start on it when you have some time. Don't forget about todos, maybe 2h is not enough to implement everything.

**Comment by criske** [comment]
@amihaiemil yep, it should be pretty straight forward for the command itself.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
