### ISSUE TITLE
Implement Commission From Contributor

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1073]
We just found out about some hidden Stripe fees which are forcing us to also charge a commission from the Contributor. Let's implement this similarly to how the Client's Commission is implemented.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-15T08:23:08.100329``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske FYI ... :(

**Comment by amihaiemil** [comment]
@zoeself status

**Comment by zoeself** [comment]
> @zoeself status

@amihaiemil this ticket is assigned to @amihaiemil since ``2021-04-05T08:23:08`` and it should be closed until ``2021-04-15T08:23:08``. Estimation is ``60`` minutes.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
