### ISSUE TITLE
InMemoryProjectsTestCase.java:23-25: Provide...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#108]
The puzzle `96-dea5d869` from #96 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/6ad0a45c0a5ca2c11d24ef72e7c75f9aa80ae7f8/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java#L23-L25

The puzzle was created by Bogdan Adrian on 25-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
This puzzle is explained [here](https://github.com/self-xdsd/self-core/pull/103#discussion_r429781986).

**Comment by criske** [comment]
I'll take it

**Comment by amihaiemil** [comment]
paid with transaction id 9XN710630H938452V

**Comment by 0pdd** [comment]
The puzzle `96-dea5d869` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
