### ISSUE TITLE
Cannot Send To US

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1092]
Seems like we cannot send cash to the US out of the box:

```java
com.stripe.exception.InvalidRequestException: Cannot create a destination charge for connected
accounts in US because funds would be
settled on the platform and the connected account is outside the platform's region.
You may use the `on_behalf_of` parameter to have the charge settle in the
connected account's country.
For more information on `on_behalf_of`, see
https://stripe.com/docs/connect/charges-transfers#on-behalf-of. If using capabilities
(e.g. `card_payments`, `transfers`), note that they affect settlement as well.
For more information on capabilities,
see https://stripe.com/docs/connect/account-capabilities.
If you still need assistance, please contact us via https://support.stripe.com/contact.;
request-id: req_kskqhJGAnIjfO8
```

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-04-24T17:40:22.131862``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
The fix is most likely to request only the Transfers capability when creating the Connect Account. At the moment Stripe also creates the Card Payments capability, which seems to be the culprit, and we don't even need it.

**Comment by amihaiemil** [comment]
com.stripe.exception.InvalidRequestException: Your platform needs approval for accounts to have requested the `transfers` capability without the `card_payments` capability. If you would like to request transfers without card_payments, please contact us via https://support.stripe.com/contact.; request-id: req_AWMZIb8QuRKqKw

**Comment by amihaiemil** [comment]
Solution seems to be to just use on_behalf_of.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
