### ISSUE TITLE
GitlabIssue.java: Start implementing the etag m... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1130]
The puzzle ``138211583`` originating from #1124 has to be resolved:

https://github.com/self-xdsd/self-core/blob/8cb7ae77ec2b14cac6418446196be3a949b2e1cb/self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java#L48-L49

"Start implementing the etag mechanism for Gitlab issues. See how it's implemented for GithubIssues.".

The puzzle was created by amihaiemil at ``2021-05-02 16:33:48 +0300``. 
Estimation is ``90 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself status

**Comment by zoeself** [comment]
> @zoeself status

@amihaiemil this ticket is not registered as a task, therefore I'm not working on it at the moment.

If you want me to take care of it, assign it to me or say "register".

**Comment by amihaiemil** [comment]
@zoeself commands

**Comment by zoeself** [comment]
> @zoeself commands

Hi @amihaiemil! Here are the commands which I understand:

* ``Hello`` -- any comment addressed to the PM containing the word **"hello"**.

  Equivalent command: ``Hi``
* ``Status`` -- any comment addressed to the PM, containing the word **"status"**. The PM will respond with the Task's status, assignee, deadline etc.
* ``Resign`` -- a task's assignee can always resign from the task, if they cannot or simply do not want to solve it. The comment should be addressed to the PM and contain the word **"resign"**. Only the task's assignee can give this command.

  Equivalent commands: ``Refuse``, ``Quit``
* ``Deregister`` -- a task can be deregistered (taken out of scope) with a comment containing the word **"deregister"**. Only a Contributor with role ``PO`` or ``ARCH`` can give this command. When a task is deregistered, the task's assignee is automatically resigned.

  Equivalent command: ``Remove``
* ``Register`` -- an Issue or PR can be registered as a Task with a comment containing the word **"register"**. Any Contributor can give this command.

  Equivalent command: ``Add``

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
