### ISSUE TITLE
GithubIssue.java: When fetching the Issue JSON,... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1131]
The puzzle ``-908291407`` originating from #1124 has to be resolved:

https://github.com/self-xdsd/self-core/blob/8cb7ae77ec2b14cac6418446196be3a949b2e1cb/self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java#L42-L43

"When fetching the Issue JSON, read the ETAG from the response http header and add it to the JSON as a string attribute.".

The puzzle was created by amihaiemil at ``2021-05-02 16:51:09 +0300``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
https://docs.github.com/en/rest/overview/resources-in-the-rest-api#conditional-requests

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-05-12T14:02:25.446781``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
