### ISSUE TITLE
GET Personal Repos ServerSide

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1163]
At the moment the personal repos are fetched client side, which has a low api rate linit (about 60 calls) and it only returns the public repos.

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
