### ISSUE TITLE
Introduce JsonResources.getWithoutCaching(...)

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1169]
This method will always do a GET: in ConditionalJsonResources it will simply delegate, without the ETag caching.

Reason: in the case of Github Pagination, the ETag call to ``...?page=2`` will NOT return the ``Link`` header, so using the ResourcePaging will not work with ETag. This can actually be a problem on Github's side (the Link header should always be returned, even in 304 NOT MODIFIED cases...).

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-06-10T10:09:56.319807``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
@amihaiemil I dunno, I'd rather store the resource headers into JsonStorage.
Caching is just a contract between ConditionalJsonResources in JsonStorage. Other JsonResources implementations or components that interact with them should know nothing about caching. 
The implementation should be straightforward. We only need to refetch on 306 to get the headers and then store'em along with etag and body. Next time on 306 it should be up to date from storage. 

But, if we really need somehow to avoid caching, we could simply pass `Cache-Control: no-cache` to request headers and we will add that feature to ConditionalJsonResources to deal with it.

**Comment by amihaiemil** [comment]
@criske I think using ``Cache-Control: no-cache`` is the simplest way actually :D 

I think storing headers into JSON storage is a bit complicated. Storing is fine, but then parsing them back into the object will be quite hard... unless we make another DB table to store them in a structured way... which seems overkill 

Plus, this fetching the Repo's is a scenario where we don't really need caching because it happens with the user's access token, not the PM's.

**Comment by criske** [comment]
> I think storing headers into JSON storage is a bit complicated. Storing is fine, but then parsing them back into the object will be quite hard... unless we make another DB table to store them in a structured way... which seems overkill

Is just a map of list o strings, shouldn't be a problem to deserialize back to map. Am I missing something  :D ?
```json
{
  "key1" : ["val1", "val2"],
  "key2" : ["val1", "val2"]
}
```

**Comment by amihaiemil** [comment]
@criske I prefer no cache also because I dont wajt to cache repo iteration - huge jsons which will occupy space for nothing :D

**Comment by amihaiemil** [comment]
@criske also in the case of repo iteration, caching means more db roundtrips and the user will wait more for the page to load

**Comment by criske** [comment]
> @criske I prefer no cache also because I dont wajt to cache repo iteration - huge jsons which will occupy space for nothing :D

If that's the case we might need in the future a scheduler to clear old entries, most likely will pile up regardless.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
