### ISSUE TITLE
GithubPersonalRepos.java: Possible bug in class FromHea... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1171]
The puzzle ``1086990812`` originating from #1166 has to be resolved:

https://github.com/self-xdsd/self-core/blob/9973ddf3a3136ccae01ea60f46bdf0adf8f48765/self-core-impl/src/main/java/com/selfxdsd/core/GithubPersonalRepos.java#L86-L90

"Possible bug in class FromHeaders. The bellow method works fine if we specify per_page=100. However, if we do not specify per_page, the default value is 30 and FromHeaders behaves strangely: at the first iteration, the next page is ?page=2 (correct), but at the second iteration, the next page is ?page=1 (it should be page=3).".

The puzzle was created by amihaiemil at ``2021-05-31 14:25:33 +0300``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
Problem seems to come from the JDK. HttpHeaders.map() does not split the header's value by comma.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-06-10T11:36:30.724139``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
https://docs.oracle.com/en/java/javase/11/docs/api/java.net.http/java/net/http/HttpHeaders.html

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
