### ISSUE TITLE
ConditionalResource for JsonStorage.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#1177]
The current problem with JsonStorage implementation is that is using a db to cache resources and thus making it unefficient.
because ConditionalJsonResources is doing extra trips to storage, one for etag check and one for body check.

This will be fixed, if JsonStorage can store the Resource instead. 
But Resource API, as it is, is not enough to be queried from db as conditional.
It needs an URI (as key), an ETag  and an optional creationDate (this will be handy at some point to remove the old entries -- eg resources related to dead projects).
So an extension for Resource interface is needed: `ConditionalResource`.

Now the JsonStorage would look like
```java
ConditionalResource getResource(URI uri)
ConditionalResource storeResource(ConditionalResource resource)
```

Using this aproach, the logic in ConditionalJsonResources#get is simplified too:
```java
Resource resource;
ConditionalResource stored = jsonStorage.getResource(uri);
if(stored != null){
  Resource remote = jsonResources.get(uri, ifNoneMatch(headers, stored.etag()))
  if(remote.code() == NOT_MODIFIED){
    resource = stored;
  }else{
 // this makes a normal resource conditional  if etag header is present
    var conditional = ConditionalResource.fromResource(uri, remote);
   if(conditional != null){
       resource = jsonStorage.storeResource(remote);
   }else{
     //etag header not found return the remote instead.
      resource = remote;
   }
  }
}else{
  Resource remote = jsonResources.get(uri);
  var condtional = ConditionalResource.fromResource(uri, remote);
  if(conditional != null){
       resource = jsonStorage.storeResource(remote);
   }else{
     //etag header not found return the remote instead.
      resource = remote;
   }
}
```

On storage side, the resource table is unchanged. It may be altered in future to support the resource creationDate, headers and even the status code (though most of time is 200).
The ConditionalResource storage implementation would take uri, etag and body from db and 200 as status code.

**Comment by zoeself** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-06-18T07:16:32.274064``.

Estimation here is ``90 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@criske thanks for fixing!

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
