### ISSUE TITLE
The PM doesn't react when the issue is closed

### ISSUE THREAD

**Issue by fedorpashin** [self-xdsd/self-core#1214]
The documentation says:
> When the Issue is closed or PR is merged, the PM will add it to the Contributor’s active Invoice.

But when I closed [this](https://github.com/fedorpashin/statistical-modeling/issues/4) issue nothing happened. Even after I linked the issue in a PR and close it while merging, the PM stubbornly doesn't react to this)

**Comment by zoeself** [comment]
@fedorpashin thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@amihaiemil I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.

**Comment by amihaiemil** [comment]
@fedorpashin The PM checks the closed Issues every 30 minutes. It doesn't react automatically when an Issue is closed because many people usually close issues by mistake (they click "Close with comment"). 

So, it should reply within 30 minutes (maximum) after an Issue is closed.

**Comment by amihaiemil** [comment]
@fedorpashin I looked in the logs and there is indeed a problem with ``fedorpashin/statistical-modeling``: Github returns status 410 GONE, for one of the Issues. Strange. Let me check further.

**Comment by amihaiemil** [comment]
@fedorpashin I think the problem should be fixed now :D

**Comment by amihaiemil** [comment]
@fedorpashin problem was that Issue number 2 from that Repo has been deleted from Github (didn't even know that was possible, sorry :D ) and Self doesn't handle that case. I'll open [an Issue](https://github.com/self-xdsd/self-core/issues/1215) for it.

**Comment by fedorpashin** [comment]
> Also, linking PRs and Issues has no effect :D

I reverted the PR, because I thought that was the problem 😄 

BTW, it would be convenient, I think, if the PM somehow understood what are the related issues and linked them automatically. For example, if comment contains "PR for #...".

**Comment by fedorpashin** [comment]
> @fedorpashin problem was that Issue number 2 from that Repo has been deleted from Github (didn't even know that was possible, sorry :D ) and Self doesn't handle that case. I'll open [an Issue](https://github.com/self-xdsd/self-core/issues/1215) for it.

Wow, okay)

**Comment by amihaiemil** [comment]
@fedorpashin

> BTW, it would be convenient, I think, if the PM somehow understood what are the related issues and linked them automatically

Maybe, but the moment I see no usecase for this :D
Each Issue or PR is treated as a separate task (Issue is for DEV role, PR is for REV role, that's it).
