### ISSUE TITLE
Get user Org Repos

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#122]
We should get the Org repos of the authenticated User, to which the User has Admin permissions.

Get Orgs: https://developer.github.com/v3/orgs/#list-your-organizations
Check Repo permissions: https://developer.github.com/v3/repos/collaborators/#review-a-users-permission-level

**Comment by criske** [comment]
@amihaiemil I'll work on this

**Comment by amihaiemil** [comment]
@criske This will be quite a lot of work. Start small, with ``Organizations :: provider.organizations()``. Organizations will be an Iterable of Organization and will represent all the orgs to which the User has admin rights.

**Comment by amihaiemil** [comment]
paid with transaction id 62H57924UM3490632
