### ISSUE TITLE
Problems with logging

### ISSUE THREAD

**Issue by fedorpashin** [self-xdsd/self-core#1226]
I can't log in, get this error:

> [invalid_user_info_response] An error occurred while attempting to retrieve the UserInfo Resource: I/O error on GET request for "https://api.github.com/user": Cannot assign requested address (Address not available); nested exception is java.net.NoRouteToHostException: Cannot assign requested address (Address not available)

The PM also doesn't work.

**Comment by amihaiemil** [comment]
@fedorpashin thanks for reporting, we'll have a look asap. The GitLab login works fine, so this must be a problem with Github.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by amihaiemil** [comment]
@fedorpashin after an app restart, it works fine now. We'll keep investigating. Seems like it was a network connection issue.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-09-29T10:55:09.864920``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@zoeself status

**Comment by zoeself** [comment]
> @zoeself status

@amihaiemil this ticket is assigned to @amihaiemil since ``2021-09-19T10:55:10`` and it should be closed until ``2021-09-29T10:55:10``. Estimation is ``60`` minutes.

**Comment by zoeself** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-09-29T10:55:10). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
Closing and moving on to #1229

**Comment by zoeself** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
