### ISSUE TITLE
Change Estimation On Label Add/Remove

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1228]
At the moment it is only possible to specify the label estimation right when the Issue is created.

We should catch the Labels Webhook event and modify the Task's estimation if an estimation label is added or removed.
If more estimation labels are found, the biggest one should be taken into account.

**Comment by amihaiemil** [comment]
@zoeself status

**Comment by zoeself** [comment]
> @zoeself status

@amihaiemil this ticket is not registered as a task, therefore I'm not working on it at the moment.

If you want me to take care of it, assign it to me or say "register".

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-10-09T09:59:48.558862``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@criske want to start on this one when you have some time? : D

If yes, remember to leave puzzles, don't solve everything here  :D

**Comment by zoeself** [comment]
@criske Don't forget to close this ticket before the deadline (2021-10-09T09:59:49). You are past the first half of the allowed period.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
