### ISSUE TITLE
Fix Occasional BindException

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#1240]
We have an occasional problem as explained [here](https://stackoverflow.com/questions/69526152/jdk-11-httpclient-bindexception-cannot-assign-requested-address).

Let's try to set the HttpClient to null and hint the gc() as explained [here](https://stackoverflow.com/questions/53919721/close-java-http-client/62735142#62735142).

If this won't work, try to use a global HttpClient for all requests.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-10-21T13:29:36.533737``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.
