### ISSUE TITLE
StoredProjectManager.java: Send a comment after updating... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1269]
The puzzle ``707400492`` originating from #1265 has to be resolved:

https://github.com/self-xdsd/self-core/blob/3edc2727a3286993bd2eb67186f8ad62ae55a894/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L55-L56

"Send a comment after updating a task's estimation inside issueLabelsChanged.".

The puzzle was created by amihaiemil at ``2021-10-30 10:34:14 +0300``. 
Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-11-09T07:40:05.497638``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@zoeself resign

**Comment by zoeself** [comment]
> @zoeself resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-11-13T09:31:41.852543``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske Don't forget to close this ticket before the deadline (2021-11-13T09:31:42). You are past the first half of the allowed period.

**Comment by criske** [comment]
@zoeself waiting for #1268

**Comment by zoeself** [comment]
> @zoeself waiting for #1268 

@criske didn't understand that, sorry.

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
