### ISSUE TITLE
StoredProjectManagerTestCase.java: Unignore/update this test onc... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1271]
The puzzle ``904709704`` originating from #1265 has to be resolved:

https://github.com/self-xdsd/self-core/blob/3edc2727a3286993bd2eb67186f8ad62ae55a894/self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java#L1832-L1833

"Unignore/update this test once the whole functionality is refactored to use Steps.".

The puzzle was created by amihaiemil at ``2021-10-30 10:34:14 +0300``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by zoeself** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-11-09T07:40:12.077754``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@zoeself resign

**Comment by zoeself** [comment]
> @zoeself resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-11-13T09:31:44.931423``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
@criske Don't forget to close this ticket before the deadline (2021-11-13T09:31:45). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by amihaiemil** [comment]
@criske when sending the 'Estimation updated' comment, can we make it more detailed please? :D 

Something like: "Estimation was changed from x min to y min at <<timestamp>>". 

Timestamp is needed because the bot will not post the same comment twice, normally, but in this case we want to allow duplicated comments in case the user changes his mind and goes back to the previous estimation or whatever : D

**Comment by zoeself** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-11-22T15:51:11.797474``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
