### ISSUE TITLE
InMemoryWallets.java: As soon as we have the Stripe... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1273]
The puzzle ``500349511`` originating from #499 has to be resolved:

https://github.com/self-xdsd/self-core/blob/463720b89b643c46b86a2ad4ab562e127b52b6c0/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java#L41-L43

"As soon as we have the Stripe wallet implemented, modify the register(...) method here to take it into account, according to the given type (at the moment, it always registers the Missing wallet).".

The puzzle was created by amihaiemil at ``2020-08-30 14:12:50 +0300``. 
Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
