### ISSUE TITLE
Paged.java: Provide paging implementation... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1274]
The puzzle ``125101892`` originating from #462 has to be resolved:

https://github.com/self-xdsd/self-core/blob/463720b89b643c46b86a2ad4ab562e127b52b6c0/self-api/src/main/java/com/selfxdsd/api/storage/Paged.java#L9-L11

"Provide paging implementation for other Self entities: Contracts, Invoices, InvoicedTasks, Tasks. As guidance use implementation for Projects: Pm/User/InMemoryProjects.".

The puzzle was created by cristianpela at ``2020-08-20 13:22:31 +0300``. 
Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
