### ISSUE TITLE
Invoices.java: . Finish writing custom Self ... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1275]
The puzzle ``1025420096`` originating from #552 has to be resolved:

https://github.com/self-xdsd/self-core/blob/463720b89b643c46b86a2ad4ab562e127b52b6c0/self-api/src/main/java/com/selfxdsd/api/Invoices.java#L10-L12

". Finish writing custom Self Exception for Invoices (InvoicesException). Also include the already written InvoiceException into InvoicesExceptions as InvoicesException.Single.".

The puzzle was created by cristianpela at ``2020-09-17 11:29:56 +0300``. 
Estimation is ``45 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
