### ISSUE TITLE
InMemoryTasksTestCase.java: Finish 'getTasksOfContributor... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1277]
The puzzle ``-1554067189`` originating from #135 has to be resolved:

https://github.com/self-xdsd/self-core/blob/192f92a7ae5778818ad212fc071713c5294d50c1/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java#L39-L41

"Finish 'getTasksOfContributor()' test case when API permits that; as in when a Task can be assigned to a Contributor.".

The puzzle was created by cristianpela at ``2020-05-30 17:37:08 +0300``. 
Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
