### ISSUE TITLE
StoredContributor.java: At the moment, method billing... 

### ISSUE THREAD

**Issue by zoeself** [self-xdsd/self-core#1286]
The puzzle ``1542307520`` originating from #985 has to be resolved:

https://github.com/self-xdsd/self-core/blob/012d1ec3ae740d51938f7ed2b22d3167458da32c/self-core-impl/src/main/java/com/selfxdsd/core/contributors/StoredContributor.java#L48-L52

"At the moment, method billingInfo() here always reads the BillingInfo from the Stripe PayoutMethod if it exists. When we will have more types of PayoutMethod, we will need to make some big changes: the BillingInfo will have to be saved on our side as a relationship to the Contributor.".

The puzzle was created by amihaiemil at ``2021-02-14 12:06:31 +0200``. 
Estimation is ``240 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
