### ISSUE TITLE
Add Custom Runtime Exceptions

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#131]
We should add and use custom runtime exception for cases such as RepoNotFound, ProjectNotFound etc. At the moment, IllegalArgumentException and IllegalStateException are being used which are too generic.

**Comment by criske** [comment]
@amihaiemil I think it's time to proper add this feature. Right now messages mapped by self-web to frontend are too generic ("Something went wrong").
I'm thinking having a base class for all self exceptions (`SelfException`). All extensions of this should not carry any message but some basic info like (keys, ids, provider name ,repo name etc.) or none, and let the `self-web` decide how the message will be presented to client, thus leaving space for internationalization.
Now with the already implemented custom exceptions, self exception tree would like:
- `SelfException`
  - `InvoiceException(invoiceId)`
    - `AlreadyPaid`
  - `RepoException(fullname, provider)`
    - `AlreadyActive`
    - `NotFound`
  - `ContractException(contractId)`
    - `Duplicate`
    - `NotFound`
  - ....

Any thoughts?: D

**Comment by amihaiemil** [comment]
@criske it's a nice idea. But internationalization of server exception messages is useless in my opinion. First of all, these exceptions should never happen, except for cases when a user bypasses front-end validation... in that case, they are probably not looking for exception messages in their language.

I like the tree. I think we should also make it Json-Polymorphic, like this:

- `SelfException extends JsonObject`
  - `InvoiceException(invoiceId)`
    - `AlreadyPaid`
  - `RepoException(fullname, provider)`
    - `AlreadyActive`
    - `NotFound`
  - `ContractException(contractId)`
    - `Duplicate`
    - `NotFound`
  - ....

This way, all exception messages could be delivered in the same JSON format, for example:

```json
{
    "message": "...exception message here..."
}
```

**Comment by criske** [comment]
@amihaiemil How about instead of implementing `JsonObject` we expose a `json()` in `SelfException` with default implementation
```java
{
    "message": this.getSelfMessage()
}
```
where `getSelfMessage()` is abstract? 
Also subclasses can add fields by overriding `json()` with `JsonPatch`

I'll try a short PR.

**Comment by amihaiemil** [comment]
@criske 

> How about instead of implementing JsonObject we expose a json()

But why would we need that? I think it's better to have uniformity and be sure all exceptions follow the same Json format :D

**Comment by criske** [comment]
@amihaiemil I was thinking of this for SelfException
```java
 public JsonObject json(){
        return Json.createObjectBuilder()
            .add("message", this.getSelfMessage())
            .build();
}

abstract String getSelfMessage();

@Override
public String getMessage() {
        throw new UnsupportedOperationException("Use getSelfMessage() to " +
            "show the exception message");
 }
```

**Comment by amihaiemil** [comment]
@criske I was thinking more like:

```java
abstract class SelfException extends AbstractJsonObject {

     SelfException(String message) {
        super(Json.createObjectBuilder().add(message).build());
    } 
}
```

and for example

```java
final class RepoNotFound extends SelfException {
    RepoNotFound() {
         super("message here...");
    }
}
```

This way, all the exceptions will always be JSON and we don't need to call any ``json()`` method :D

**Comment by amihaiemil** [comment]
@criske buuut, I just realized SelfException will also need to extends RuntimeException. 

And because we cannot extend 2 classes, this means SelfException will need to implement all the methods of JsonObject. That will be ugly.

We go with your ``json()`` method then :D

**Comment by criske** [comment]
@amihaiemil yep we would have to write delegates for each impl, to avoid multiple inheritance :D

**Comment by amihaiemil** [comment]
paid with transaction id 7DF492353L617541T
