### ISSUE TITLE
Tasks.java:30-31: Implement and unit test...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#136]
The puzzle `133-7376f99a` from #133 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/d8f98bcb2e001d80c36155956d22cd836c246efc/self-api/src/main/java/com/selfxdsd/api/Tasks.java#L30-L31

The puzzle was created by @amihaiemil on 29-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
waiting for #134

**Comment by criske** [comment]
No worries about the bounty :D. I was about to take one of the issues
tomorrow morning. But sure assign me, I'll take care of it this evening, if
not, tomorrow morning for sure.

**Comment by amihaiemil** [comment]
@criske whenever you want/have time, it's not urgent.

**Comment by 0pdd** [comment]
The puzzle `133-7376f99a` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
