### ISSUE TITLE
ContributorTasks.java:21-24: In `InMemoryTasks.java`...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#141]
The puzzle `134-f73a4154` from #134 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/b423ede7651e1e797eec92eb6094b5006f55d452/self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContributorTasks.java#L21-L24

The puzzle was created by cristianpela on 30-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil sign me up

**Comment by 0pdd** [comment]
The puzzle `134-f73a4154` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
