### ISSUE TITLE
StoredUser.java:35-38: At the moment the User's...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#146]
The puzzle `142-5967597e` from #142 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/3dbc4da6d0e648fae8fd20591ea9ed2cc2f9b0e7/self-core-impl/src/main/java/com/selfxdsd/core/StoredUser.java#L35-L38

The puzzle was created by @amihaiemil on 30-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this

**Comment by 0pdd** [comment]
The puzzle `142-5967597e` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
