### ISSUE TITLE
GithubSelf.java:38-40: Implement User.repos(). It should...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#15]
The puzzle `13-b311c7f8` from #13 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/e8313b595e44eb3d86868787cc87a41613adf5a3/self-core-impl/src/main/java/com/selfxdsd/core/GithubSelf.java#L38-L40

The puzzle was created by @amihaiemil on 16-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
typo in the puzzle: Repos should represent the user's repositor**ies**
