### ISSUE TITLE
Might use enums instead of constants (Provider.Names, Contracts.Role).

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#154]
Provider.Names could be an enum.
Same for Contracts.Role.

I've spent about 10 minutes, to figure out why SelfUser#signUp test in `self-storage` was failling, just to realize that I've used a bogus 'provider' lol. 
(StoredUser was replacing any other provider outside github with gitlab).

**Comment by amihaiemil** [comment]
@criske Nah, sorry. I hate Enums from the bottom of my heart. Every time I look at an Enum I can never tell which is the value, which is the key, what will toString() etc. 

So, we stick with Strings. My guess is that, even if they were Enums, you would have the same problem if you specified ``Provider.Names.GITHUB`` instead of ``*.*.GITLAB``.

**Comment by criske** [comment]
I'm the other way, I really don't like constants, especially when I'm writing apis. :D. 
But anyway we might need to throw an exception in StoredUser#provider if the provider is different than github or gitlab. Seems odd to return a Gitlab for some random provider name, even for an empty string.

**Comment by amihaiemil** [comment]
@criske 

> But anyway we might need to throw an exception in StoredUser#provider...

Well, I was actually thinking to change the signature of ``signUp`` to accept the User's parameters as input variables, instead of a ``User``. 

Looking at it now, it doesn't really make sense to expect a ``User`` which is actually not signed up yet. 

But I'll look over this tomorrow.

**Comment by criske** [comment]
> But Enums are also constants. Only with a useless layer of abstraction on top of it, if you ask me.

The problem with constants is that you don't have input control out of the box. 
Android has a cool way to achieve that with constants by using annotations.
https://developer.android.com/reference/androidx/annotation/StringDef
