### ISSUE TITLE
InMemory.java:33-36: Write unit tests for all the...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#16]
The puzzle `13-32838750` from #13 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/e8313b595e44eb3d86868787cc87a41613adf5a3/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java#L33-L36

The puzzle was created by @amihaiemil on 16-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll give a try

**Comment by amihaiemil** [comment]
@criske remember, you don't have to solve the task completely. Start with a few tests and leave a todo in the code, which will become the next task.

**Comment by 0pdd** [comment]
The puzzle `13-32838750` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@criske Thanks for solving this. Send me your PayPal e-mail address, please :)
