### ISSUE TITLE
Implement the Invoice

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#161]
A Contract should have a corresponding Invoice containing all the tasks that have been finished by the Contributor.

**Comment by criske** [comment]
Sign me up

**Comment by amihaiemil** [comment]
@criske Actually, it's a 1-to-many relationship. A Contract has more Invoices, but only one of them is "active" (not yet paid) -- we will always add a finished task to the active Invoice, the one that is not yet paid. 

If all the invoices are paid, we create a new one.

**Comment by amihaiemil** [comment]
payment done with transaction id: 46151150Y9859444R
