### ISSUE TITLE
Invoices.java:11-12: Implement and test InMemoryInvoices....

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#164]
The puzzle `163-912d9b79` from #163 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/27bc74cf7e8c6ecdda356183621da6f6a9845ddf/self-api/src/main/java/com/selfxdsd/api/Invoices.java#L11-L12

The puzzle was created by cristianpela on 06-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this

**Comment by amihaiemil** [comment]
paid with transaction ID 9RV72720Y86457822

**Comment by 0pdd** [comment]
The puzzle `163-912d9b79` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
