### ISSUE TITLE
InMemoryInvoices.java:19-23: Refactor and test...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#175]
The puzzle `165-63222a61` from #165 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/101eccca529220e334e10b7bae5db6e8c070d447/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryInvoices.java#L19-L23

The puzzle was created by cristianpela on 07-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this.
I'll focus on testing and leave refactoring part for another puzzle, if that's ok.

**Comment by 0pdd** [comment]
The puzzle `165-63222a61` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
paid with transaction id 1BD17495F00273448
