### ISSUE TITLE
ProjectTasks.ofContributor should return tasks from the project only

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#186]
At the moment this method returns all the tasks of the given contributor, yet it should return only the tasks from the Project represented by ``ProjectTasks``.

Basically, we just need to filter the encapsulated ``List<Task>``.

**Comment by amihaiemil** [comment]
@criske Can you please fix this when you have the time? :D 
It's a simple change inside ``ofContributor`` method: instead of calling the storage and getting all the tasks of the contributor, we just have to filter the List we have inside ProjecTasks.

**Comment by criske** [comment]
Sure, I think the same bug is in the ContributorTasks#ofProject too. Should I fix there too?

**Comment by amihaiemil** [comment]
If you can do it fast and in $5, yes. If not, open another issue :D

**Comment by amihaiemil** [comment]
paid with transaction id 7FJ66972SC5278153
