### ISSUE TITLE
Contract.java:33-35: Finish implementing and testing...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#203]
The puzzle `204-4a2ef409` from #204 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/a9a1a6c2d13883f574b10fd1656ef0eb33e3fda5/self-api/src/main/java/com/selfxdsd/api/Contract.java#L33-L35

The puzzle was created by cristianpela on 11-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this

**Comment by amihaiemil** [comment]
@criske sure, go ahead

**Comment by amihaiemil** [comment]
paid with transaction id: 2UG77083V2195670R

**Comment by 0pdd** [comment]
The puzzle `204-4a2ef409` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
