### ISSUE TITLE
Implement equals/hashCode for StoredContributor and others

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#208]
StoredContributor, StoredContract, StoredProject etc should implement equals and hashcode based on their IDs.

**Comment by criske** [comment]
I'll work on this

**Comment by amihaiemil** [comment]
sure, go ahead

**Comment by amihaiemil** [comment]
@criske One thing: in equals, when you check for the object's type with ``instanceof``, use the Interface, not the Class. 

This is a mistake I find in most equals functions: they ask the objects to be of the same class instead of the same interface.

**Comment by criske** [comment]
yep, that's what I did

**Comment by amihaiemil** [comment]
paid with transaction id 7JC54856LK201074A
