### ISSUE TITLE
StoredProjectManager.java:39-40: Test equals and hashcode...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#212]
The puzzle `212-4e897150` from #212 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/dcce7935bae7f0c70a326e00e7ca7765c40db779/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L39-L40

The puzzle was created by cristianpela on 16-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by ANadrowski** [comment]
@amihaiemil I'd like to work on this issue.

**Comment by amihaiemil** [comment]
paid with transaction id 5YK98516841893910

**Comment by ANadrowski** [comment]
@amihaiemil I think you can close this issue.

**Comment by amihaiemil** [comment]
@ANadrowski this is funny, it should have been closed automatically by 0pdd... thanks!
