### ISSUE TITLE
ContractTasks.java:19-21: Method Tasks.ofContract() has...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#223]
The puzzle `207-01b671c5` from #207 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/70f4cab97afddac5d059742746b1db38c41b4fbc/self-core-impl/src/main/java/com/selfxdsd/core/tasks/ContractTasks.java#L19-L21

The puzzle was created by @amihaiemil on 22-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this

**Comment by amihaiemil** [comment]
@criske I think it's better to leave this task for someone else. It's a good start for a beginner, as they will see how these objects are constructed and used.

**Comment by criske** [comment]
sure

**Comment by ANadrowski** [comment]
Hello @amihaiemil 

To be honest, the hardest part for a beginner here is understand how to run the projects together when it is needed (self-web, self-storage, self-core and self-pm). I mean.. for example: when you are implementing some new feature in "self-core", how do you run it? what are the steps? I know that it is a dumb question, but the answer is not so obvious to beginners..

**Comment by amihaiemil** [comment]
@ANadrowski 

Well, "features" in self-core are actually new classes and methods. You cannot run self-core on its own because it's just a component. You write unit tests in order to verify that the class or method you implemented is correct.

Same for self-storage: it's just a component which you "run" by writing tests. self-storage has more sophisticated tests which run against a real database - they are called integration tests.

self-web and self-pm are spring boot apps which you can run from IntelliJ, but manual testing is not so valuable. In the case of self-web, for instance, we might write Selenium tests later on: UI Automation for end-to-end automated testing.

**Comment by ANadrowski** [comment]
Hi @amihaiemil, thanks for the explanation! :)

**Comment by ANadrowski** [comment]
It looks like that to solve this issue is needed to implement the tests for Task.ofContract() of the classes _ContributorTasks.java_,
_ProjectTasks.java_ and _UnassignedTasks.java_. If possible, can you assign it to me? then I will try to solve it in the next few days.

**Comment by amihaiemil** [comment]
@ANadrowski Sure, but start with just one of them, you don't have to do them all in this task :)

**Comment by ANadrowski** [comment]
Hi guys,

I am trying to implement a test in the class `ProjectTasksTestCase` but I am getting a `NullPointerException` in the statement `MatcherAssert.assertThat(tasks.ofContract(contractId)`. Do you have any idea why is it happening? Is there something wrong with the mock of `task`?

```
    /**
     * Should return tasks for contract.
     */
    @Test
    public void returnTasksForContract() {
        final Contract.Id contractId = new Contract.Id("foo", "mihai",
                Provider.Names.GITHUB, Roles.DEV);

        final Contributor mihai = Mockito.mock(Contributor.class);
        Mockito.when(mihai.username()).thenReturn("mihai");
        Mockito.when(mihai.provider()).thenReturn(Provider.Names.GITHUB);
        final Task task = Mockito.mock(Task.class);
        Mockito.when(task.assignee()).thenReturn(mihai);
        Mockito.when(task.role()).thenReturn(Roles.DEV);

        final Storage storage = Mockito.mock(Storage.class);

        final Tasks tasks = new ProjectTasks(
                "foo", Provider.Names.GITHUB,
                List.of(
                        task
                ),
                storage
        );

        MatcherAssert.assertThat(tasks.ofContract(contractId),
                Matchers.iterableWithSize(1)
        );
    }
```

Thanks in advance.

**Comment by criske** [comment]
@ANadrowski It looks like Task doesn't have its Project mocked.

**Comment by amihaiemil** [comment]
@ANadrowski I can't look now, I don't have my laptop. But as @criske said, NPE is most likely because of an unfinished mock.

Try debugging :)

**Comment by ANadrowski** [comment]
@criske @amihaiemil thank you. I will take a look asap :)

**Comment by ANadrowski** [comment]
@amihaiemil I just sent the PR #261. Please take a look when possible. Thanks.

**Comment by 0pdd** [comment]
The puzzle `207-01b671c5` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
