### ISSUE TITLE
Github.java:40-43: Abstract all the HTTP calls behind an...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#226]
The puzzle `190-ecea2376` from #190 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/084dd0f1809ac20f1e052c64b61086bbb475f70a/self-core-impl/src/main/java/com/selfxdsd/core/Github.java#L40-L43

The puzzle was created by amihaiemil on 22-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske we actually come back to your idea of abstracting the HTTP calls. But with some different naming :D

**Comment by criske** [comment]
@amihaiemil nice :D, much easier for testing now.
