### ISSUE TITLE
JsonResources, accessToken: passing an interface instead of string. 

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#242]
Providers might use different headers for authenticated requests.
Right know JdkHttp is using github's auth header _Authentication_, but Gitlab, as far as I know, is using a different header: _Private-Token_.
So the interface AccessToken might have to methods to implement: 
- header : the header name (Authentication, Private-Token)
- value: the token

For example a GithubAccessToken would look like:
- header: `Authentication`
- value: `token <token>`

**Comment by amihaiemil** [comment]
@criske It's a good idea, thanks :)

**Comment by criske** [comment]
I'll work on this
