### ISSUE TITLE
GithubIssueComments.java:14-15: Implement and test the...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#244]
The puzzle `100-a80e16f6` from #100 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/0468b4566626fc97f7663b30f844e53dfce59b7e/self-core-impl/src/main/java/com/selfxdsd/core/GithubIssueComments.java#L14-L15

The puzzle was created by cristianpela on 30-Jun-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll work on this.

waiting for #237

**Comment by amihaiemil** [comment]
@criske sure, I'll take care of that asap

**Comment by amihaiemil** [comment]
@criske I've implemented the POST method in #245 :)

**Comment by criske** [comment]
@amihaiemil Nice, just one question: should I test using Grizzly, or just unit test it with mocks?

**Comment by amihaiemil** [comment]
@criske You can write a todo for the unit tests. We'll write unit tests with a mock version of JsonResources. I'll implement that a bit later in #246. 

It doesn't really make sense to Grizzly tests, since the only valuable assertion would be URI -- JdkHttp post already has integration tests using Grizzly.

**Comment by amihaiemil** [comment]
paid with transaction id: 0ER62346G31483402

**Comment by 0pdd** [comment]
The puzzle `100-a80e16f6` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
