### ISSUE TITLE
Organizations.java:8-9: Start implementing Github...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#259]
The puzzle `122-8525164d` from #122 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/4c219b0434b6a8b5b679f2180083f1d6bdd515df/self-api/src/main/java/com/selfxdsd/api/Organizations.java#L8-L9

The puzzle was created by cristianpela on 02-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil Can I work on this?

**Comment by amihaiemil** [comment]
@criske Yes, but don't write a lot of code, please. Start small, with listing the Organizations :D

**Comment by 0pdd** [comment]
The puzzle `122-8525164d` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
