### ISSUE TITLE
ProjectTasks.java:43-44: It needs to implement the unit...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#262]
The puzzle `223-49114d3d` from #223 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/2617be14026749cece9979c1db7da101d8421661/self-core-impl/src/main/java/com/selfxdsd/core/tasks/ProjectTasks.java#L43-L44

The puzzle was created by @ANadrowski on 06-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by ANadrowski** [comment]
Hi @amihaiemil, could I work on this?

**Comment by amihaiemil** [comment]
@ANadrowski Sure, but only if you want to. This month I have no budget for bounties, so I can't send you any cash. 
The budget for bounties will come back in August :)

**Comment by ANadrowski** [comment]
@amihaiemil This is not a problem, assign it to me please :)

**Comment by ANadrowski** [comment]
@amihaiemil just sent the PR #264 :)

**Comment by 0pdd** [comment]
The puzzle `223-49114d3d` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
