### ISSUE TITLE
GithubOrganization.java:14-15: Continue to implement and...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#275]
The puzzle `122-8be42be5` from #122 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/da7cd6e5975c7e6947df2cd4d9a4984a1eee470d/self-core-impl/src/main/java/com/selfxdsd/core/GithubOrganization.java#L14-L15

The puzzle was created by cristianpela on 09-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll continue to work on this.

**Comment by 0pdd** [comment]
The puzzle `122-8be42be5` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
