### ISSUE TITLE
User.java:30-31: Allow {@link User} interface to have...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#277]
The puzzle `277-e4f1192a` from #277 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/e7388d374744703552f38187140311f9e3b17777/self-api/src/main/java/com/selfxdsd/api/User.java#L30-L31

The puzzle was created by cristianpela on 09-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this

**Comment by amihaiemil** [comment]
@criske sure, go ahead :)
