### ISSUE TITLE
Write unit tests for other User implementations.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#290]
Write tests for `BaseSelf.Authenticated` and `PmUser` in order to increase test coverage.

**Comment by ANadrowski** [comment]
@amihaiemil I'd like to work on this. Could you assign it to me?

**Comment by amihaiemil** [comment]
@ANadrowski sure, go ahead :D

**Comment by amihaiemil** [comment]
@ANadrowski FYI, I put a bounty on this ticket : D

**Comment by ANadrowski** [comment]
@amihaiemil It was a busy week here, but I will take a look asap :D

**Comment by amihaiemil** [comment]
@ANadrowski no worries, whenever you have time :D

**Comment by ANadrowski** [comment]
Hi @amihaiemil  
I'm sorry for the delay here. 
Feel free to remove the bounty but if possible let it still assigned to me and I will try to solve it in the next days (probably next weekend)... thanks.

**Comment by amihaiemil** [comment]
@ANadrowski no problem, whenever you have time 👍

**Comment by ANadrowski** [comment]
@amihaiemil thanks :)

**Comment by ANadrowski** [comment]
Hi @amihaiemil @criske could you give me a tip here?

A good test for _BaseSelf.Authenticated_ should be to create an instance of it, passing the values in the constructor (User and token) and test its methods (_username()_, _email()_, _provider()_ and _projects()_)?

... and the same for _PmUser_?

I observed that the _BaseSelf.Authenticated_ is used in the test _platformLoginWorks()_, but there it is just tested if _Self_ is an instance of BaseSelf.Authenticated. So I think that the new test should test its methods. 

Am I right?

Thank you

PS. I'm sorry for this dumb question...

**Comment by amihaiemil** [comment]
@ANadrowski Yes, a good unit test usually means you instantiate the object and then make assertions on the methods.

But the key is to mock the dependencies. For instance, you want to see that ``Authenticated.username()`` returns the username but you are not interested in the ``username()`` method from the ``User``. So you mock the User.

Here is an example: 

```java
final User user = Mockito.mock(User.class);
Mockito.when(user.username()).thenReturn("john");

final Authenticated authenticated = new Authenticated(user, "tok3n");
MatcherAssert.assertThat(
    authenticated.username(),
    Matchers.equalsTo("john")
);
```

**Comment by ANadrowski** [comment]
@amihaiemil that is awesome, thanks! :D

**Comment by ANadrowski** [comment]
@amihaiemil 
The Authenticated unit test is almost ready, it needs just to test provider() yet -> https://github.com/ANadrowski/self-core/blob/c10e6f5e5a792f350084d07cb1f05d0970393580/self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java#L138
I am going to try to do it soon.

But I am having a problem with the PmUser class because it is an inner class and it is private, then I cannot call it on the test -> https://github.com/ANadrowski/self-core/blob/c10e6f5e5a792f350084d07cb1f05d0970393580/self-core-impl/src/test/java/com/selfxdsd/core/managers/StoredProjectManagerTestCase.java#L386

I am using the same package "com.selfxdsd.core.managers" so it should work, but it is not working because it is an inner class.. I think..

What do you think about it?

Thanks.

**Comment by amihaiemil** [comment]
@ANadrowski yes, it is private, that's why you can't use it. But don't worry about PmUser right now.

Don't forget, you don't have to solve the whole task. Unit tests for Authenticated are enough, just leave a todo for the rest, which will become a new task.

**Comment by criske** [comment]
@ANadrowski The`PmUser` could be tested indirectly by calling:
`User user = new StoredProjectManager(....).provider().repo("some-repo").owner()` :)

**Comment by ANadrowski** [comment]
@amihaiemil @criske 
To test the method bellow (of the class `BaseSelf. Authenticated`) the right approach should be to verify if `.provider()` returns a provider with the same token that I used when I created an Authenticated instance? (i.e. `new Authenticated(user, "tok3n")`)

```
@Override
 public Provider provider() {
     return this.user.provider().withToken(this.accessToken);
 }
```
Thanks

**Comment by criske** [comment]
@ANadrowski 
I think verifying that provider `withToken` is called is enough. 
`when(user.provider()).thenReturn(mockedProvider)` 
then
`verify(mockedProvider).withToken(anyString())`
If you really want to check if correct token is passed you could use an [ArgumentCaptor](https://www.javadoc.io/doc/org.mockito/mockito-core/2.6.9/org/mockito/ArgumentCaptor.html) instead of `anyString()`

**Comment by ANadrowski** [comment]
@criske thank you!

**Comment by ANadrowski** [comment]
@criske if I got it well, the `verify(mockedProvider).withToken(anyString())` tests if the method  `.provider() `was called at least once inside the test, right? Even if I am not using the new instance `provider1` created here: `final Provider provider1 = new Authenticated(user, "tok3n").provider(); `right?

Right now the test is ok, what do you think about it? please see it if possible:

https://github.com/ANadrowski/self-core/blob/c5f97e2ca6954d269656526770d59a6ac0e4b6f0/self-core-impl/src/test/java/com/selfxdsd/core/SelfCoreTestCase.java#L118

**Comment by amihaiemil** [comment]
@ANadrowski Please make a Pull Request and we will discuss there. The test doesn't look bad, but I have a few comments :)

**Comment by ANadrowski** [comment]
@amihaiemil It is ok, I will try to do it tonight :)

**Comment by ANadrowski** [comment]
@amihaiemil last question here: Is it ok to put 2 @ todo inside the same class? The class  `StoredProjectManager` already has a @ todo. But I’d like to add a @todo to create a unit test for PmUser. Or should I update the @todo that already exists there?

**Comment by amihaiemil** [comment]
@ANadrowski yes, it's ok to add another todo. Never edit existing todos since they already have a corresponding Issue :)

**Comment by ANadrowski** [comment]
@amihaiemil thank you :+1:

**Comment by ANadrowski** [comment]
@amihaiemil  Just sent the PR, please take a look when possible #346 :)

**Comment by amihaiemil** [comment]
paid with transaction id 5DT58440YW416563P
