### ISSUE TITLE
Webhook Event resolve could be done by ProjectManager instead.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#293]
From an "use-case" point of view, I think this is ProjectManager's responsability.
An event processing flow would look like:
`Event e = buildEventFromPayload(json, provider, secret, storage)`
and then:
`storage.projects().findProjectById(e.repoFullName(), e.provider()).projectManager().resolve(event)`

But there is a problem with this aproach. PM doesn't know on which project to work. Having `Project` in `Event`,
as in current API, doesn't make the cut, since nothing stops a client to pass a `Project` that is not managed by `ProjectManager`,
unless we check, but that require an extra db call for pm's projects.

To solve this I think we should make `StoredProjectManager` aware of which project is currently working, by adding a field let's say `activeProject`(so not part of `ProjectManager` API). 
This field will be set only once via a setter in self-storage when we create a project in `SelfProjects#projectFromRecord(Record)`.

Now in `StoredProjectManager#resolve` we only need to check if `activeProject` is set and matches `Event`'s project id(repo+provider).This also will make `Event#project()` obsolete, since we only need the project id.
Still will be a problem with the `webhook-secret` check but we can just adding it to `StoredProjectManager` when setting the `activeProject`. 

This also simplify the PM API, methods like `newIssue`, `reopenedIssue` will not be needed anymore, only as helpers in `StoredProjectManager`.

**Comment by amihaiemil** [comment]
@criske I'm actually no satisfied with either solutions. I don't really like how it looks so far and I definitely don't like private helper methods. I will think of a more elegant design...

**Comment by amihaiemil** [comment]
@criske I think I'll do it similarly to how I built another chatbot, a few years ago: the PM will have a set of composed capabilities, which will resolve to some Steps that he will execute: https://github.com/opencharles/charles-rest/blob/master/src/main/java/com/amihaiemil/charles/github/Action.java#L87

**Comment by criske** [comment]
@amihaiemil Even with that solution,  I think PM still needs a reference to its project. 

 How about we inject the project with its webhook secret when we call `projectManager()` in `StoredProject`?
`public ProjectManager projectManager() {`
 `return new StoredProjectManager(this.projectManager.id(),this.projectManager.username(), this.provider(),null, this.storage, this, this.webHookToken);`
 `}`
Now `StoredProjectManager` has no api private methods and is immutable again.
Or even better, we can have a method in `ProjectManager` API  `ProjectManager::withActiveProject(Project, String)`  and now
`projectManager()` in `StoredProject` will return `this.projectManager.withActiveProject(this, secret)`

**Comment by amihaiemil** [comment]
@criske The PM will have access to the Project via the Event. The PM can also check if the Event belongs to him by doing: 

``assert this.username.equals(event.project().projectManager().username()``.  :D
