### ISSUE TITLE
User.java:30-31: Continue with GitlabOrganizations by...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#298]
The puzzle `298-42a404da` from #298 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/dd2648290b4baad63189299c60deb8f2e33daac2/self-api/src/main/java/com/selfxdsd/api/User.java#L30-L31

The puzzle was created by cristianpela on 18-Jul-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
paid with transaction id 7WV57429PP6023543

**Comment by amihaiemil** [comment]
@criske why is still still open, didn't you remove the puzzle from the code? :D

**Comment by amihaiemil** [comment]
@criske yes, I saw you removed it... strange.
