### ISSUE TITLE
InMemory.java:36-38: Implement the projects() storage. A...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#32]
The puzzle `29-ee978689` from #29 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/ef44858c55ac86905ea0da7cafa1c1a4737cdc11/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemory.java#L36-L38

The puzzle was created by @amihaiemil on 18-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by 0pdd** [comment]
The puzzle `29-ee978689` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@criske Thanks for solving this. Send me your PayPal e-mail address, please :)
