### ISSUE TITLE
GitlabRepo.java:38-39: Implement the GitLab...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#330]
The puzzle `328-f56725d1` from #328 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/cb5176d9bad035b2480dce0ed5ffac741432a161/self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java#L38-L39

The puzzle was created by @amihaiemil on 30-Jul-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske Wanna take this one? :D

**Comment by criske** [comment]
@amihaiemil sure

**Comment by criske** [comment]
waiting for #334

**Comment by criske** [comment]
https://github.com/self-xdsd/self-core/blob/a2e0cedf38cd7ca2f8f83a85cd16a00b1dfeb0d4/self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java#L73
`URI.create("https://gitlab.com/api/v4/projects/"+ repoName)`
@amihaiemil There is a small bug here, in fact 2 bugs:
- ?owned=true must be added or else will list random public repos besides the ones owned by user
- repoName must be composed with owner user name ex: mihai/repoName and then encoded in uri. [Namespaced path encoding](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding). Right now is working only if we pass the actual repo id for repoName.

Should I fix this in this PR or open new issue?

**Comment by amihaiemil** [comment]
@criske It's better if you open 2 Issues, one for each bug, with a detailed description :D 
Then, this Issue will wait until those 2 are fixed. I think it's cleaner this way.

**Comment by amihaiemil** [comment]
paid with transaction id 7RL00662N0186031R

**Comment by criske** [comment]
@amihaiemil I forgot the remove the puzzle, sorry. Can I make a quick pr and remove it?

**Comment by amihaiemil** [comment]
@criske yes, sure

**Comment by 0pdd** [comment]
The puzzle `328-f56725d1` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
