### ISSUE TITLE
JsonResources post/patch/put methods should pass a JsonValue for body.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#334]
Sometimes we want to pass a plain string value spoofed as a JsonValue. For example adding a collaborator to a Gitlab project
require a plain string in the request body. [doc link](https://docs.gitlab.com/ee/api/members.html#add-a-member-to-a-group-or-project)

**Comment by amihaiemil** [comment]
@criske sure, go ahead :D

**Comment by amihaiemil** [comment]
paid with transaction id 6JY97201U85955444
