### ISSUE TITLE
GitlabRepo.java:73: `repoName` in Uri must be composed with owner's username.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#337]
https://github.com/self-xdsd/self-core/blob/a2e0cedf38cd7ca2f8f83a85cd16a00b1dfeb0d4/self-core-impl/src/main/java/com/selfxdsd/core/GitlabRepo.java#L73

repoName must be composed with owner user name and then encoded.
See [Namespaced path encoding](https://docs.gitlab.com/ee/api/README.html#namespaced-path-encoding) 
For example if repo name is _my_repo_ and owner username is _mihai_ then repo uri must look like:
`https://gitlab.com/api/v4/projects/mihai%2Fmy_repo`

**Comment by criske** [comment]
waiting for #336

**Comment by amihaiemil** [comment]
paid with transaction id 89J27219H5980601U
