### ISSUE TITLE
GitlabOrganizationRepos.java:85-91: The method...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#343]
The puzzle `333-0a2c981a` from #333 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/06892dc4f6e9605255204dded3d6fe5d209e5c31/self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java#L85-L91

The puzzle was created by @amihaiemil on 05-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske Poti sa te uiti peste asta daca ai timp, te rog? Nu mi-am dat seama ce valoare trebuie sa ii dau la ``Gitlab.createFromName(...)`` si am pus empty-string: 

https://github.com/self-xdsd/self-core/blob/master/self-core-impl/src/main/java/com/selfxdsd/core/GitlabOrganizationRepos.java#L97

**Comment by criske** [comment]
@amihaiemil E simplu, problema e in documentatia astora de la Gitlab :D. A trebuit sa-mi fac propriul org cu proiecte ca sa 
imi dau seama ca repo uri se poate extrage direct din json. E acolo un camp nedocumentat `_links` care-l contine printre altele.
Imediat fac un pr.

**Comment by amihaiemil** [comment]
paid with transaction id 6J217317GG981440G

**Comment by 0pdd** [comment]
The puzzle `333-0a2c981a` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
