### ISSUE TITLE
InMemoryProjects.java:45-46: Write unit tests for paging...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#353]
The puzzle `346-3112900e` from #346 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/c570220d2565ab0d3ecd28b30c46c2d78502af27/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjects.java#L45-L46

The puzzle was created by cristianpela on 06-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll finish this, but without a bounty please :D. This is still part of #341 imo.

**Comment by amihaiemil** [comment]
@criske Please continue and also leave puzzles to continue implementing this mechanism for other entities as well. 
Paging is not so urgent at the moment: I would continue with replacing the Lists with Streams accross entities (there are still many that use Lists).

**Comment by amihaiemil** [comment]
paid with transaction id 1CW69358YB242091F

**Comment by 0pdd** [comment]
The puzzle `346-3112900e` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
