### ISSUE TITLE
Start implementing GitLab Provider.

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#36]
Following the pattern of the Github Provider, we should implement one for GitLab as well. First, we should check the API of GitLab and see how we can fetch a Repo, assign Issues etc.

**Comment by criske** [comment]
I'll take it

**Comment by amihaiemil** [comment]
@criske I suggest to start with very little code. First, check GitLab's RESTful API and see how we can fetch a Repo, its Issues etc. 

Document what you find here, in this ticket, please :)

**Comment by criske** [comment]
To get all repos owned by an autheticated user:  https://gitlab.com/api/v4/projects/?owned=1
To get one repo:   https://gitlab.com/api/v4/projects/:repoId

**Very important**: all these calls must have in their header either a private-token or a oauth access- token. I've tested with private-token
https://docs.gitlab.com/ee/api/#personalproject-access-tokens

**Comment by amihaiemil** [comment]
@criske and is there a way to get the **public** repos, or one public repo of a User without authentication? GitHub allows us to do that, I think GitLab should allow it as well :D

**Comment by criske** [comment]
Is possible, but in that case I think we'll have to use the gitlab domain associated to that user (like: gitlab.example.com), and that will brake the User API. 
I will dig more, I'm new to Gitlab.

**Comment by amihaiemil** [comment]
@criske 

>  but in that case I think we'll have to use the gitlab domain associated to that user (like: gitlab.example.com)

No, I don't think so. We'll work only with the public GitLab, at GitLab.com.

**Comment by amihaiemil** [comment]
@criske As far as I can see, we can read the public Repos with by accessing https://gitlab.com/api/v4/projects/ 

So surely, there must be a way to get the public repos of a user, too. 

It's enough info for now, thanks! I'll send you the bounty for doing this documentation work and then we can start with the code.

**Comment by criske** [comment]
Without auth, only public repos:  https://gitlab.com/api/v4/users/:userName/projects/

**Comment by amihaiemil** [comment]
@criske perfect, thanks

**Comment by criske** [comment]
One more thing, just checked: if we attach the access token to that endpoint, it will list the private repos too.

**Comment by amihaiemil** [comment]
@criske Thank you for solving this!
