### ISSUE TITLE
Project should be registered after pm is invited and webhook created.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#362]
Right now project is saved first to storage in `Repo#activate`.
But there are some problems with this aproach:
- if one of the steps `PmInvite` or ` WebhookSetup` fail, then the project will be saved in a bad state.
- webhook secret is created internally in `ProjectManager#asign`. But we will need to store hook `id` too besides `secret`, for the time we want to deactivate the project (will also delete the hook from provider). So the best place to create the `Webhook(id, secret)` obj will be in the `WehookSetup`.

Project activation flow might look like:
- select repo -> `Repo` - `repo `
- pick and invite pm based on repo provider -> `ProjecManager` - `pm`
- register repo webhook -> `Webhook(id, secret)` - `webhook`

If all 3 actions passes (basically a transaction) then we can call
`projects.register(repo, pm, webhook)` -> `Project` or `pm.asign(repo, webhook)` -> `Project`

Project deactivation flow:
- delete project from storage by project key
- remove pm from repo collaborators
- delete project wehook from provider by using stored webhook id

**Comment by criske** [comment]
might be related to #361

**Comment by amihaiemil** [comment]
@criske But I think we can iterate over a Repo's hooks and see their URLs, right? This way, we can deactivate all hooks that have a ``self-xdsd.com`` URL. So we don't need to save any hook ID. 

Otherwise, this seems like a good idea, but it doesn't necessarily have to be a transaction. As it is now, we register the Repo and later, if InvitePm or SetupWebhook fails, we can display a warning message on the UI and ask the user to do these 2 steps manually. I think it's easier this way.

**Comment by criske** [comment]
>  But I think we can iterate over a Repo's hooks and see their URLs, right? This way, we can deactivate all hooks that have a `self-xdsd.com` URL. So we don't need to save any hook ID.

I guess that will work too :)

> Otherwise, this seems like a good idea, but it doesn't necessarily have to be a transaction. As it is now, we register the Repo and later, if InvitePm or SetupWebhook fails, we can display a warning message on the UI and ask the user to do these 2 steps manually. I think it's easier this way.

I for one I wouldn't let the owner to setup the webhook manually, but anyway there are slim chances to fail that step :D.
The problem is going to be InvitePm.
For Gitlab is easy, they don't have an invite system; the pm is added without confirmation. (will receive a notif email that they were assigned and that's it -- though they can reject it from the same mail).
For Github does the owner should know if the pm accepted the invitation, so the project is truly active or just assumes that sometimes in the future will accept the invite?

> Well, at the moment InvitePm and SetupWebhook are failing silently... we could add an exception mechanism later, so we can inform the user if one of them faill.

Does Github have webhooks for when an invite was declined?
Just skimming over their doc maybe we could subscribe for [members events](https://developer.github.com/webhooks/event-payloads/#member), for the case when current pm decides to leave and reassign the project to other pm. Gitlab has them too but are part of the system hooks (global webhooks basically) [user_add_to_team/user_remove_from_team](https://docs.gitlab.com/ee/system_hooks/system_hooks.html) -- dumb, I know.

**Comment by amihaiemil** [comment]
@criske 
>  For Github does the owner should know if the pm accepted the invitation, so the project is truly active or just assumes that sometimes in the future will accept the invite?

The invitation has to be accepted by the PM. We have an automatic mechanism for that as well, it's already implemented in self-pm:

https://github.com/self-xdsd/self-pm/blob/551909191d27a7bc159ea360eeda72c286201311/src/main/java/com/selfxdsd/selfpm/AcceptInvitations.java#L71-L91

So every 10min, each PM will check their invitations and accept anything they got. There is no scenario in which an invitation is declined.

**Comment by criske** [comment]
@amihaiemil gotcha :). Should we take then in consideration the corner case when PM decides to leave? I mean nothing could stop them to go to github/gitlab and leave the project.

**Comment by amihaiemil** [comment]
@criske well, maybe later. They are chatbots, so they'll do exactly what we tell them haha

**Comment by criske** [comment]
@amihaiemil  rofl completly missed out that they are bots. 
You could close this issue if you want.
