### ISSUE TITLE
StoredProjectManager.java:42-43: Unit tests have been...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#363]
The puzzle `290-4f83021f` from #290 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/f9c60a30c685e1bba74849ebf578eb8a112231e3/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L42-L43

The puzzle was created by Aislan Nadrowski on 07-Aug-20. 

Estimate: 15 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by HoreaPetrila** [comment]
I can take this one, sorry for the period of inactivity, I've had my Bachelor Exam

**Comment by amihaiemil** [comment]
@HoreaPetrila no problem, welcome back!

**Comment by HoreaPetrila** [comment]
```
remote: Permission to self-xdsd/self-core.git denied to HoreaPetrila.
fatal: unable to access 'https://github.com/self-xdsd/self-core.git/': The requested URL returned error: 403
```
No access to push anymore, maybe?

**Comment by amihaiemil** [comment]
@HoreaPetrila nobody has push access on the main repo, you have to fork it and push to your fork, then make a Pull Request

**Comment by amihaiemil** [comment]
paid with transaction id 0UA53070TH8285745

**Comment by 0pdd** [comment]
The puzzle `290-4f83021f` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
