### ISSUE TITLE
BasePaged should have `totalRecords` up to date. 

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#374]
After inserting records into storage, `BasePaged#totalRecords` should reflect that when calling `Based#totalPages()`.
Instead of an `int`, passing a `Supplier<Integer>` to BasedPaged constructor should fix that.
The `Supplier`, internally, should query the `table` size.

**Comment by amihaiemil** [comment]
@criske well, since you opened the Issue, let's fix it :D

**Comment by amihaiemil** [comment]
paid with transaction id 07N0426116971273J
