### ISSUE TITLE
StoredProject.java:42-44: At the moment the wallet()...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#378]
The puzzle `376-1e018104` from #376 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/355d899cd35a74275e252214f74c26bbe52f065f/self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java#L42-L44

The puzzle was created by @amihaiemil on 11-Aug-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll try on this. This is just having a `Wallet::getWalletById(id)` in Projects?

**Comment by amihaiemil** [comment]
@criske Nope. The StoredProject will encapsulate the walletId (read from the DB). Based on this walletId, we will have a Wallet implementation which will probably talk to a payments microservice. 

Let's mark this task as "postponed" for now, as there are many unknowns still.

**Comment by criske** [comment]
@amihaiemil That's I was my train of thought, I think :D. 
Implementation of wallet in StoredProject would simply looked like `this.storage.projctes().getWalletById(this.walletId)` and the return would be a Wallet (currently stubbed) else `Wallet.Missing`. I assumed that the talk with the payment service will be when call `available`.

**Comment by amihaiemil** [comment]
@criske Yes, the talk will happen in the ``available()`` method, but there will be no ``getWalletById(...)``. Simply:

```java
public Wallet wallet() {
    final Wallet wallet;
    if(this.walletId == null) {
       wallet = new Wallet.Missing();
   } else {
       wallet = new SvcWallet(this.walletId); //some Walled implementation which talks to the microservice.
   }
}
```

So until we have SvcWallet there is not much to do :D

**Comment by criske** [comment]
@amihaiemil gotcha, so no extra static info about wallet stored in storage apart of `id`.

**Comment by 0pdd** [comment]
The puzzle `376-1e018104` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
