### ISSUE TITLE
Move unit tests comparesStoredContributorObjects and verifiesStoredContributorHashcode

### ISSUE THREAD

**Issue by ANadrowski** [self-xdsd/self-core#387]
Move the unit tests comparesStoredContributorObjects and verifiesStoredContributorHashcode
from ProjectContributorsTestCase.java to StoredContributorTestCase.java

**Comment by ANadrowski** [comment]
@amihaiemil Let me do it (without bounty). 
Thanks.

**Comment by amihaiemil** [comment]
@ANadrowski sure, go ahead
