### ISSUE TITLE
InMemoryTestCase.java:18-20: Continue writing unit tests...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#39]
The puzzle `16-dcb763b9` from #16 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/63a4615b45f656e8d02ecdfdf0adc78eabe75b55/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTestCase.java#L18-L20

The puzzle was created by @amihaiemil on 19-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by HoreaPetrila** [comment]
I can take this one.

**Comment by 0pdd** [comment]
The puzzle `16-dcb763b9` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@HoreaPetrila please, send me your PayPal e-mail address :)

**Comment by amihaiemil** [comment]
paid with transaction ID: 2NC782506L140584T
