### ISSUE TITLE
ProjectContributors.java:43-44: When electing a...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#404]
The puzzle `402-0cf23d35` from #402 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/278603527b12bdbfaa7345110a99c3d578e154e1/self-core-impl/src/main/java/com/selfxdsd/core/contributors/ProjectContributors.java#L43-L44

The puzzle was created by cristianpela on 15-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske wanna take care of it? By the way, I think it's easier if you just use the encapsulated Project (no need to read the Project from the contributor's Contract every time).

**Comment by criske** [comment]
@amihaiemil sure

**Comment by amihaiemil** [comment]
paid with transaction id 8VA15175A0094282N

**Comment by 0pdd** [comment]
The puzzle `402-0cf23d35` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
