### ISSUE TITLE
InMemoryTasksTestCase.java:40-41: Update InMemoryTasks...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#443]
The puzzle `439-396801f4` from #439 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/68fe1ab395e4fbd74066d228b666e0637d1ba3c8/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java#L40-L41

The puzzle was created by cristianpela on 18-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil i'll finish this quick, no bounty needed.
It looks like `InMemory` is very useful to test `steps/conversations`, just using Mockito is getting too hard/verbose there.

**Comment by 0pdd** [comment]
The puzzle `439-396801f4` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
