### ISSUE TITLE
Implement Deregister conversation

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#466]
In this conversation, if the event type is "deregister",  the PM should unassign the Task and remove it from the DB. This will allow the project to have open Issues which are not tracked by the PM. 

Only the PO and ARCH roles should be able to give this command.

**Comment by amihaiemil** [comment]
@criske Wanna start this one? The first thing we need is a sketch of Deregister and a Step which verifies the role of the author.

See how the Resign conversation and the AuthorIsAssignee check are implemented :D

**Comment by criske** [comment]
@amihaiemil ok

**Comment by criske** [comment]
@amihaiemil there is a problem, we don't have a way to remove a task from db.

**Comment by amihaiemil** [comment]
paid with transaction id 9SM62392XE1717021
