### ISSUE TITLE
Gitlab.java:37: Continue adding integration tests for...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#47]
The puzzle `27-ef64e245` from #27 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/bf48b434e2fd44a2a2aacafe7315959d97b83b31/self-core-impl/src/main/java/com/selfxdsd/core/Gitlab.java#L37-L37

The puzzle was created by cristianpela on 20-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll take it
