### ISSUE TITLE
Tasks.java:30-31: Implement Task::Tasks#remove(Task)...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#471]
The puzzle `471-41d301f9` from #471 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/6e62de8855ac0aabf9a9aca06e73e3589f6f4b6d/self-api/src/main/java/com/selfxdsd/api/Tasks.java#L30-L31

The puzzle was created by cristianpela on 20-Aug-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil sign me up
