### ISSUE TITLE
Tasks.java:30-32: Update filter implementations of...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#478]
The puzzle `476-448b8be8` from #476 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/b6c303ec4cae3a1e2a9b763505e01a157ba6a092/self-api/src/main/java/com/selfxdsd/api/Tasks.java#L30-L32

The puzzle was created by cristianpela on 21-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by criske** [comment]
@amihaiemil I'll work on this, no bounty needed

**Comment by amihaiemil** [comment]
@criske sure, go ahead (at least a little cash is needed :D )

**Comment by amihaiemil** [comment]
paid with transaction id 4KG87642R2803252U

**Comment by 0pdd** [comment]
The puzzle `476-448b8be8` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
