### ISSUE TITLE
ContractInvoices.java:121 - "Cannot create an Invoice outside of a Contract. Call #ofContract(...) first."

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#500]
https://github.com/self-xdsd/self-core/blob/44a76f60a459b26eff803b7a6116d7736f283a77/self-core-impl/src/main/java/com/selfxdsd/core/contracts/invoices/ContractInvoices.java#L121

Error was triggered by self-storage `SelfInvoices` and catched by frontend while trying to list project's contracts for https://github.com/self-xdsd/self-web/issues/70

Edit: It happens when calculating contract's value, which is using the active invoice. If there is no active invoice, a new one will be created and will trigger the bug.

**Comment by criske** [comment]
@amihaiemil I'll fix this.

**Comment by amihaiemil** [comment]
@criske What's the bug exactly? I don't understand :D

**Comment by criske** [comment]
@amihaiemil 
`StoredContract` when it calculates the value:
https://github.com/self-xdsd/self-core/blob/4686ad83f4c82761ec4b946eca72bb4b89e87c6f/self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java#L201

Call directly the storage Invoices#active, but that throws exception:
https://github.com/self-xdsd/self-storage/blob/22800e2fe7b2bf5f5431b78e9b9dbc2c3c75b4a5/src/main/java/com/selfxdsd/storage/SelfInvoices.java#L121

**Comment by criske** [comment]
@amihaiemil It might be a self-storage bug cause StoredContracts calls the active, the right way
https://github.com/self-xdsd/self-core/blob/4686ad83f4c82761ec4b946eca72bb4b89e87c6f/self-core-impl/src/main/java/com/selfxdsd/core/contracts/StoredContract.java#L187

**Comment by criske** [comment]
@amihaiemil Yeah it's a `SelfInvoices` bug. Will throw the exception, regardless if is called from `ContractInvoices` or not.

**Comment by criske** [comment]
@amihaiemil Might be missing feature afterall. Don't see anywhere in `SelfInvoices`  where an `Invoice` is created.

**Comment by criske** [comment]
@amihaiemil nvm `self-web` has an outed `self-storage` version.

**Comment by amihaiemil** [comment]
@criske ok :D
