### ISSUE TITLE
InMemoryWallets.java:40-42: As soon as we have the Stripe...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#504]
The puzzle `499-d1da8a5e` from #499 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/dd1c7da3149b8a17b48c4b61e0283c4c9488eeeb/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java#L40-L42

The puzzle was created by amihaiemil on 30-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
