### ISSUE TITLE
Task.java:33-35: Task api should expose resignations(),...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#511]
The puzzle `498-73b39da9` from #498 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/94f90d5cf4bea267f9f83296b879ae8dd68133b2/self-api/src/main/java/com/selfxdsd/api/Task.java#L33-L35

The puzzle was created by cristianpela on 30-Aug-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll continue on this.

**Comment by 0pdd** [comment]
The puzzle `498-73b39da9` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
