### ISSUE TITLE
Self API should have access to Contributors.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#521]
This will be useful when for example a `Project` owner will add a new `Contract` and the `Contributor` username field has an "autocomplete" feature.

**Comment by amihaiemil** [comment]
@criske it's not a bad idea, but originally I was thinking to use Github's API for the autocomplete feature. Otherwise it won't be very useful until we have a lot of contributors registered in the system :D

**Comment by criske** [comment]
@amihaiemil But what happens when github user is not a contributor... will be registered when we add the contract?

**Comment by amihaiemil** [comment]
@criske yes, exactly. We register the contributor when some project owner adds the first contract. 
Did you have something else in mind? :D

**Comment by criske** [comment]
@amihaiemil Nope, is just right now we throw ISE when adding a contract for an ureg contributor instead of register them.

**Comment by amihaiemil** [comment]
@criske right, that should change, definitely. I'll open an Issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this, no bounty needed.

**Comment by amihaiemil** [comment]
paid with transaction id 4HJ09009KG512722G
