### ISSUE TITLE
SelfException.java:34-36: Replace old custom exceptions...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#524]
The puzzle `524-1af26f28` from #524 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/a0e404fcee284f24f2431ecf186ffa46af7abac6/self-api/src/main/java/com/selfxdsd/api/exceptions/SelfException.java#L34-L36

The puzzle was created by cristianpela on 07-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this - no bounty needed is just a refactor.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
