### ISSUE TITLE
InMemoryContracts.java:36-38: Implement this class and...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#53]
The puzzle `42-89e036d3` from #45 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/f206cd3aa5d7f66961e062d0dd8d41fb9dd8c6e7/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java#L36-L38

The puzzle was created by @amihaiemil on 20-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
@criske Do you want to solve this? It shouldn't be hard to implement. A Contract is basically the association (many-to-many) between a Project and a Contributor. It's primary key should be the project id and the contributor id.

**Comment by criske** [comment]
Sure, I'll take it

**Comment by 0pdd** [comment]
The puzzle `42-89e036d3` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
