### ISSUE TITLE
Task.java:33-34: Write custom SelfExceptions for Tasks...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#549]
The puzzle `550-0614a150` from #550 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/15ace4b74f4e17288bfe5e19aaabe20a58d6cdbe/self-api/src/main/java/com/selfxdsd/api/Task.java#L33-L34

The puzzle was created by cristianpela on 11-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this.
Also need to remove puzzle from #546

**Comment by amihaiemil** [comment]
@criske sure, go ahead :D

**Comment by amihaiemil** [comment]
paid with transaction id 12831170NT728673X

**Comment by 0pdd** [comment]
The puzzle `550-0614a150` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
