### ISSUE TITLE
Invoices.java:8-10: Finish writing custom Self Exception...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#555]
The puzzle `552-d847b7f6` from #552 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/63e628b1aa96c74819562e3251662067ed9fb700/self-api/src/main/java/com/selfxdsd/api/Invoices.java#L8-L10

The puzzle was created by cristianpela on 17-Sep-20. 

Estimate: 45 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
