### ISSUE TITLE
StoredProjectManager.java:45-47: When reviewing the...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#564]
The puzzle `562-63248b5a` from #562 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/f5ca9431a732f117e579293b99c93e2e9c2b8561/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L45-L47

The puzzle was created by amihaiemil on 26-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll work on this

**Comment by amihaiemil** [comment]
@criske sure, go ahead :D

**Comment by amihaiemil** [comment]
paid with transaction ID 8LD813704J098315R

**Comment by 0pdd** [comment]
The puzzle `562-63248b5a` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
