### ISSUE TITLE
Check for closed Issue when reviewing Unassigned Tasks

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#568]
When reviewing the unassigned tasks we should check if the Issue has been closed in the meantime. If it's been closed, it should not be assigned to anyone.

At the moment, this check is missing: https://github.com/amihaiemil/docker-java-api/issues/358

**Comment by criske** [comment]
@amihaiemil  I'll work on this. We should also remove the task if the issue is closed, right?

**Comment by amihaiemil** [comment]
@criske sure, go ahead

**Comment by amihaiemil** [comment]
@criske sorry, just now I noticed the question. Yes, if the Issue is closed we should also remove the Task.

**Comment by amihaiemil** [comment]
paid with transaction id 0C13209254449470T
