### ISSUE TITLE
StoredProjectManager.java:46-48: When checking if task...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#572]
The puzzle `571-e9749a10` from #571 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/6c11b71aa73edd06c7e86adaa0c250511c273118/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L46-L48

The puzzle was created by cristianpela on 30-Sep-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
@amihaiemil I'll continue on this

**Comment by amihaiemil** [comment]
paid with transaction iD 20X48950L40983547

**Comment by 0pdd** [comment]
The puzzle `571-e9749a10` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
