### ISSUE TITLE
Before registering a new task we should check if the issue is not closed.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#587]
When processing "register" event we should check if the issue is not closed first.

https://github.com/self-xdsd/self-core/blob/41e3831136a9c542851ff74aa18c444019fe62c2/self-core-impl/src/main/java/com/selfxdsd/core/managers/Register.java#L69

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by criske** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@criske this issue is already registered as a task.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-15T12:49:50.725967``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2020-10-15T12:49:50). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
