### ISSUE TITLE
UnassignTask Step should register the resignation too.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#589]
https://github.com/self-xdsd/self-core/blob/41e3831136a9c542851ff74aa18c444019fe62c2/self-core-impl/src/main/java/com/selfxdsd/core/managers/UnassignTask.java#L74
Otherwise the contributor who wishes to resign will reenter the election pool.

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-15T21:49:50.734438``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@criske this ticket is assigned to @criske since ``2020-10-05T21:49:50`` and it should be closeduntil ``2020-10-15T21:49:50``. Estimation is ``60`` minutes.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
