### ISSUE TITLE
Message response for closed ticket "status" command.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#591]
https://github.com/self-xdsd/self-core/blob/75f4306e35274b93511ede763a8ca3bc1a0958eb/self-core-impl/src/main/java/com/selfxdsd/core/managers/Status.java#L75
We should have a message response for a "status" command associated with an issue that is closed. Right now project manager treats the issue as an opened one. 
PM should respond something along the lines:

_This ticket is not registered as a task, therefore I'm not working on it at the moment._

_If you want me to take care of it, please reopen it. However, reopening Issues is not encouraged -- it's better if you open new tickets instead._

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-16T19:19:50.768056``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
paid with transaction id 81R08964LG676832G

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
