### ISSUE TITLE
Implement PmProjects

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#60]
PmProjects will implement Projects and will represent the projects assigned to a certain ProjectManager.

**Comment by amihaiemil** [comment]
@criske Ce incerc sa fac e sa nu "sparg" interfetele. De exemplu exista, ``Projects.assignedTo(projectManagerId)`` care intuitiv ar returna o Lista de Project. Dar nu vreau sa fac asta, vreau sa returnez tot o instanta de ``Projects`` care sa reprezinte proiectele PM-ului.

Dar imi dau seama acum ca nu e deloc usor, intervin inclusiv probleme de paginare... 

Nici nu vreau sa returnez o simpla Lista de Project pentru ca dupa aia asta genereaza cod procedural: daca vreau de exemplu proiectele unui PM si dintre acelea sa aflu care carui User apartin, ce fac, ca am o Lista cheala -- scriu o functie privata pe undeva care sa intoarca pe dos Lista aia...

In schimb, daca nu "sparg" interfata Projects, ea are (sa va avea) metoda ``ofUser(User user)``. Atunci query-ul e ft simplu: ``projects.assignedTo(projectManagerId).ofUser(user)``.

Nu stiu daca are sens ce zic...? :D

**Comment by criske** [comment]
Nu imi este clar un lucru: ce o sa returneze
 `projects.assignedTo(projectManagerId).ofUser(user).assignedTo(otherProjectManagerId).`  Va lua in considerare si `user` cand va efetua query-ul?
Interesant articolul, btw :)

**Comment by amihaiemil** [comment]
@criske da, ideea ar fi ca daca se chain-uiesc mai multe call-uri se ia in considerare tot contextul:

``projects.assignedTo(projectManagerId).ofUser(user).assignedTo(otherProjectManagerId)`` -- asta intotdeauna ar returna ``Projects.Empty``, deoarece avem o data proiectele manage-uite de primul, dintre care le luam pe cele ale unui anumit user (dar, din nou, ele sunt manage-uite de primul), asa ca al doilea call, avand id-ul altui manager, nu va avea niciodata rezultate.

O varianta ar fi sa se arunce o exceptie, devreme ce query-ul practic nu are sens :D

**Comment by criske** [comment]
Mersi de explicatie, maine cred ca o sa deschid un issue sa rescriu InMemoryContracts.

**Comment by amihaiemil** [comment]
@criske o sa continui cu ce avem, chiar daca m-am lovit acum de niste probleme, sa nu stau blocat. Dar numai ca idee, daca chiar nu iese, vor fi niste schimbari maricele, haha
