### ISSUE TITLE
Implement the StripeWallet

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#604]
Wallet implementation representing a Stripe wallet.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-20T15:39:50.842353``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@criske I'll solve this one

**Comment by criske** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign

@criske ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-20T15:49:50.776447``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
@charlesmike resign

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is registered as a task, I will assign it to someone soon.Needed role here is ``DEV`` and estimation is ``60 minutes``.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.
