### ISSUE TITLE
StripeWallet.java:36-38: Implement method pay(...) here...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#606]
The puzzle `604-dc7ff9e3` from #604 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/8678a79607ba7a2b8778502bcacfaca6b5421d2a/self-core-impl/src/main/java/com/selfxdsd/core/projects/StripeWallet.java#L36-L38

The puzzle was created by @amihaiemil on 10-Oct-20. 

Estimate: 60 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@charlesmike please pay attention to this new issue.

**Comment by charlesmike** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-20T16:09:50.848837``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
waiting for #599

**Comment by criske** [comment]
@amihaiemil I think we will need to modify `Wallet#pay(...)` to return `Wallet` instead, in order to reflect a successful payment in 
`Wallet#cash()` (`limit - invoice.totalAmmount`). Any reason why the current API  for pay returns a payed `Invoice`?

**Comment by amihaiemil** [comment]
> Any reason why the current API for pay returns a payed Invoice?

@criske Good question. Yes, maybe it's better to return the Wallet.

I also realized, we should implement the "waiting" functionality too -- it seems like we need it badly :D

**Comment by criske** [comment]
@amihaiemil "waiting" , as in waiting for a stripe webhook event of a successful payment intent, thus keeping the invoice in a pending state?

**Comment by amihaiemil** [comment]
@criske "waiting" as in, the ``waiting`` command for the PM: for instance in this ticket it should stop counting the deadline because you said ``waiting for #598`` :D

**Comment by charlesmike** [comment]
@criske Don't forget to close this ticket before the deadline (2020-10-20T16:09:50). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 8F043479Y6898584P

**Comment by 0pdd** [comment]
The puzzle `604-dc7ff9e3` has disappeared from the source code, that's why I closed this issue. //cc @charlesmike

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
