### ISSUE TITLE
Implement Issues.search(...)

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#610]
We should have a method for search: ``Issues :: issues.search(text, labels...)``

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.
