### ISSUE TITLE
Offer method Contract.update(HourlyRate)

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#625]
We should have a way of updating a Contract's hourly rate.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.
