### ISSUE TITLE
Make Self.java unaware of different platform logins.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#63]
Instead of having a `githubLogin(...)` `gitlabLogin(...)` , we could have a single method like `login(Login)`
where implementations of Login will take care of that logic (`GithubLogin`, `GitlabLogin` etc).
`Login` interface would have single a method `signUp(Storage)`.
Also the `signUp` helper method from SelfCore could be moved to an abstract BaseLogin class. 

This way the Self API will not change each time a new platform login is added.

**Comment by amihaiemil** [comment]
@criske it might be a good idea. Let's mark it as an enhancement, but postpone it for now. I want to focus on getting a first complete version of the core, first.

**Comment by amihaiemil** [comment]
@criske can you take care of this? I started implementing the web module and it turns out, it would be really useful.

**Comment by criske** [comment]
Yup

**Comment by amihaiemil** [comment]
paid with transaction id: 1B097818PG677570F

thanks!
