### ISSUE TITLE
Add Method Repo.star()

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#630]
We should implement this method for GithubRepo, as explained here: https://developer.github.com/v3/activity/starring/#star-a-repository-for-the-authenticated-user

The star() method in GitlabRepo should just throw ``UnsupportedOperationException`` for now.

Since the URI does not respect the normal fluency, you will have to just build it entirely in the method (https://api.github.com/user/starred/:owned/:name). 

You can get the repo owner and name by parsing the URI encapsulated by GithubRepo and taking the last two path parts.

A unit tests using MkContainer should be enough.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by amihaiemil** [comment]
@ak2703 Please take care of this when you have some time.

**Comment by amihaiemil** [comment]
paid with transaction id 1N03482294543235X
