### ISSUE TITLE
GithubInvitation.java:40-41: After we have the method...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#632]
The puzzle `629-041ddd1b` from #629 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/87796b04c713eadae872281bb545bcba1dd47f1f/self-core-impl/src/main/java/com/selfxdsd/core/GithubInvitation.java#L40-L41

The puzzle was created by @amihaiemil on 18-Oct-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@charlesmike please pay attention to this new issue.

**Comment by charlesmike** [comment]
@0pdd thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by 0pdd** [comment]
> @0pdd thank you for reporting this. I'll assign someone to take care of it soon.

  I see you're talking to me, but I can't reply since I'm not a chat bot.

**Comment by amihaiemil** [comment]
waiting for #630

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-10-28T12:09:50.755590``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
@amihaiemil What will happen if PR for task is created before the deadline but merged after it?

**Comment by amihaiemil** [comment]
@criske the PR has to be merged *before* the deadline. If the deadline passes, the Task is taken away and no payments will be made to the Contributor -- payments will be made only to the PR reviewer (that is treated as a different Task).

Maybe we could allow the PO or ARCH to reassign a Contributor even if they were resigned.

**Comment by criske** [comment]
@amihaiemil But can't this be abused? The contributor submits the pr before the deadline, but the reviewer waits to pass the deadline and only they will be paid :D

**Comment by amihaiemil** [comment]
@criske Well, yes. But Self is supposed to be a platform for teams that already work together and trust each other.

Not matter how many rules we add, we can't really prevent the kind of abuse you're talking about.

**Comment by amihaiemil** [comment]
paid with transaction id 4GY59943F9057953T

**Comment by 0pdd** [comment]
The puzzle `629-041ddd1b` has disappeared from the source code, that's why I closed this issue. //cc @charlesmike

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
