### ISSUE TITLE
Mark a Contract for Deletion

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#636]
Contract should have an attribute called ``markedForDelete`` which will be a LocaDateTime.

When a user clicks "delete contract", this field will be assigned the current date and, only after a number of days (maybe a month), the contract will actually be deleted.

This mechanism is needed in order to ensure that the contract's invoice gets paid.

If a Contract is marked for removal, no new tasks should be assigned to it.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.
