### ISSUE TITLE
GithubStars.add() Should Build Its Own URI

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#643]
At the moment, GithubStars accepts its URI attribute from the parent Repo. Unfortunately, this is not correct, because the Stars URI does not follow the same fluency (the path is ``/user/starred/:owner/:repo`` instead of ``/repos/:owner/:repo/stars``)

Don't forget to also modify the tests and assert that the path is built correctly.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil task successfully removed.

**Comment by amihaiemil** [comment]
already fixed.
