### ISSUE TITLE
Implement Commits of a Repo

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#646]
We should have access to the Repo's Commits and one Commit's Comments, so the PM can post a comment there (for instance, if there was an error parsing TODOs into new tickets).

interface Commits extends Iiterable<Commit> {
    Commit findBySha(...);
}
interface Commit {
    Comments comments;
}

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-06T18:49:51.701586``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything - you can solve it only partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike status

**Comment by charlesmike** [comment]
> @charlesmike status

@amihaiemil this ticket is assigned to @amihaiemil since ``2020-10-27T18:49:51`` and it should be closeduntil ``2020-11-06T18:49:51``. Estimation is ``60`` minutes.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
