### ISSUE TITLE
Add PO Contract When Activating Repo

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#649]
When a user activates their Repo, we should also add them as a Contributor and register a PO Contract (hourly rate $25 by default).

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-09T09:12:41.192214``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske can you take care of this when you have some time? : D

**Comment by criske** [comment]
@amihaiemil sure

**Comment by amihaiemil** [comment]
paid with transaction id 52W345514G336722W

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
