### ISSUE TITLE
Unassign Issue On Deadline Resign

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#652]
If the deadline passes, we should also resign the contributor from the Issue. Otherwise, the PM will elect them again: https://github.com/decorators-squad/eo-yaml/issues/415#issuecomment-719625161

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-09T17:55:26.594810``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by criske** [comment]
@amihaiemil that's weird, thought this use case was covered here
https://github.com/self-xdsd/self-core/blob/7a2f72819e65af6b5b90147e5d090c7c1cfec3a3/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L458

**Comment by amihaiemil** [comment]
@criske Problem is here: https://github.com/self-xdsd/self-core/blob/7a2f72819e65af6b5b90147e5d090c7c1cfec3a3/self-core-impl/src/main/java/com/selfxdsd/core/managers/StoredProjectManager.java#L335

Task gets unassigned, contributor resignation is registered, but he remains Issue assignee, so he's elected without any further checks. 

We just need to unassign the Issue, that's all :D

**Comment by criske** [comment]
@amihaiemil  gotacha.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
