### ISSUE TITLE
Implement RegisterResignation Step

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#653]
We need this intermediary step.
At the moment, step ``UnassignTask`` regsiter an ``ASKED`` Resignation.

However, we don't always have to register a resignation when unassigning a task: for exapmle, if the Task is deregistered by the PO, we should not register a resignation of the assignee, since it's not their decision to resign and they also did not miss any deadline.,

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-10T13:42:23.813336``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
