### ISSUE TITLE
GithubIssue: Get RepoFullName from URL

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#660]
At the moment we read the repoFullname from the ``repository_url`` attribute. However, the ``pull_request`` JSON that comes from a webhook event does not have this attribute.

We should instead get the repoFullName from the ``url`` attribute which is present everywhere.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-14T14:25:26.343008``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
