### ISSUE TITLE
Offer method Issue.body()

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#666]
Let's do it

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-16T12:39:00.549238``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@criske I'll take care of this :D

**Comment by criske** [comment]
@amihaiemil sure, I was almost done to finish it :D

**Comment by amihaiemil** [comment]
@criske sorry :D I still sent a payment for it, with id 3Y322916UC4410741

**Comment by criske** [comment]
@amihaiemil  Thank you, but please don't, it was small task anyway. :D 
I'll put a deadline on my tasks from now on (3 days deadline is enough for me instead of 10).

**Comment by amihaiemil** [comment]
@criske no worries
