### ISSUE TITLE
Send Project name and Description on Stripe Wallet Setup

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#670]
When we create a Project's Stripe Wallet, we should send the project name and description to Stripe, otherwise the Customers Table will be empty on the Stripe Dashboard:

<img width="1116" alt="Screenshot 2020-11-06 at 21 19 01" src="https://user-images.githubusercontent.com/6305156/98405938-c26b3380-2075-11eb-95a6-4a937d78be97.png">

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-16T21:19:40.201749``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
