### ISSUE TITLE
Remove Method Commits.received(...)

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#673]
There are too many differences between a Commit coming from the API and a Commit coming as part of a push Event.

Therefore, we will always fetch the commit from the API and we do not need method Commits.received(...) anymore. Remove it from the Commits interface, GithubCommits class and also any unit tests should be removed.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-17T16:29:23.886521``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike resign

**Comment by charlesmike** [comment]
> @charlesmike resign

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@charlesmike register

**Comment by charlesmike** [comment]
> @charlesmike register

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-19T12:07:21.316254``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@andreoss Don't forget to close this ticket before the deadline (2020-11-19T12:07:21). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@andreoss I'm closing this since you resolved it. Don't forget to send me your PayPal address so I can wire you the payment.

**Comment by charlesmike** [comment]
@andreoss thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
