### ISSUE TITLE
InMemoryTasksTestCase.java: Finish 'getTasksOfContributor... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#679]
The puzzle ``135-200b416a`` originating from #135 has to be resolved:

https://github.com/self-xdsd/self-core/blob/6971b4d16e37bac82e4bcfd5c9eab3466c54be32/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryTasksTestCase.java#L39-L41

"Finish 'getTasksOfContributor()' test case when API permits that; as in when a Task can be assigned to a Contributor.".

It was created by cristianpela on 2020-05-30T14:37:08Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@charlesmike thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
