### ISSUE TITLE
Take provider into account when picking a PM

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#68]
We should take the provider into account when choosing a PM for a Repo - e.g. if it's a Github Repo, then only PMs working at Github should be considered.

**Comment by BogdanAdrian11** [comment]
I'll take this.

**Comment by amihaiemil** [comment]
@BogdanAdrian11 send me your PayPal e-mail address, please

**Comment by amihaiemil** [comment]
paid with transaction ID: 9D8623163J2317806
