### ISSUE TITLE
StoredProject.java: Implement the deactivate meth... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#681]
The puzzle ``31-902d1319`` originating from #31 has to be resolved:

https://github.com/self-xdsd/self-core/blob/6971b4d16e37bac82e4bcfd5c9eab3466c54be32/self-core-impl/src/main/java/com/selfxdsd/core/projects/StoredProject.java#L42-L44

"Implement the deactivate method which should remove the Project form the DB (it means Self will stop managing it). Return the corresponding Repo when done. Don't forget the tests.".

It was created by @amihaiemil on 2020-05-19T16:22:34Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@charlesmike thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
