### ISSUE TITLE
GithubIssue.java: Initially, all the Issues wil... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#683]
The puzzle ``128-bc49fe1d`` originating from #128 has to be resolved:

https://github.com/self-xdsd/self-core/blob/6971b4d16e37bac82e4bcfd5c9eab3466c54be32/self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java#L44-L46

"Initially, all the Issues will have the DEV or REV role. In a future version, we will set an Issue's role based on labels set by the user.".

It was created by amihaiemil on 2020-05-27T20:15:08Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@charlesmike thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
