### ISSUE TITLE
Add Method Contracts.remove(Contract)

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#686]
Let's implement and test this method.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-20T18:36:41.943243``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@andreoss Don't forget to close this ticket before the deadline (2020-11-20T18:36:41). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@andreoss thanks for solving this. I still haven't got your PayPal address, don't forget about it please.

**Comment by charlesmike** [comment]
@andreoss thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
