### ISSUE TITLE
PM reassigns resigned Issue

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#688]
When I resign from a ticket, the PM should not assign it to me again, ever: https://github.com/self-xdsd/self-core/issues/687

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-20T19:17:22.732873``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@andreoss I'm pretty sure the problem is inside the Resign conversation, the order in which the steps are composed. At the moment, it is UnassignTask -> RegisterResignation and it should most likely be the other way around (RegisterResignation -> UnassignTask). 

This is because RegisterResignation will not do anything if the Task has no assignee.

**Comment by charlesmike** [comment]
@andreoss Don't forget to close this ticket before the deadline (2020-11-20T19:17:22). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@andreoss do you think you can fix this today? I would like to make a release. 

THe only think you have to do, I believe, is switch the order of those 2 steps (UnassignTask and RegisterResignation) inside the Resign Conversation.

**Comment by amihaiemil** [comment]
@andreoss thanks for solving it. Don't forget about the PayPal address...

**Comment by charlesmike** [comment]
@andreoss thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
