### ISSUE TITLE
Self's Commission Should Be Percentage of Payment

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#711]
At the moment we have a fixed commission (e.g. 1 EUR/invoiced task). However, this will not work because of Stripe's fees which are calculated differently from what we initially thought.

In order to make sure Self is not losing money, its commission should be a percentage from the Invoice's value.
In other words, a percentage from each payment being made. Minimum viable commission is 5%.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-11-30T17:14:14.779520``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske FYI, this is also quite a big change...

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
