### ISSUE TITLE
Missing Wallet Should Update Cash and Register Invoice as Paid

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#720]
When paying an invoice with the Missing wallet, we should update its cash (deduct the payment value) and also mark the invoice as paid.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-07T10:32:24.405369``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by criske** [comment]
@amihaiemil There's is a small problem here. `Missing` wallet part of `api` module and paying an invoice requires `StoredInvoice` which is in `impl`. Should we move `Missing` to `impl` where it can be tested too? 
Also should we then rename it to `FakeWallet` to easier assess the wallet type?

**Comment by amihaiemil** [comment]
@criske yes, definitely. I forgot about that part.

**Comment by amihaiemil** [comment]
paid with transaction id 0TU17860VP8671302

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
