### ISSUE TITLE
Pagination of PM Projects

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#750]
At the moment the PM selects only the first 10 of their projects.
It should iterate over all the pages.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-12T21:35:35.122396``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske Can you have a look here please?

You don't have to fix it in this task, I think it's too much work for 60min.
Just have a look and post an update on it, why it happens and how it will be fixed, in the next task.

I don't really remember how the pagination works and everything :D

**Comment by criske** [comment]
Replacing with 'Page.all()' in constructor should do it. It's a quick fix, I'll take care of it tomorrow :D
Until the fix 'PmProjects(..).page(Page.all())' is equivalent.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
