### ISSUE TITLE
GithubIssue.java: Labels API: should be able to... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#761]
The puzzle ``305-e93af154`` originating from #305 has to be resolved:

https://github.com/self-xdsd/self-core/blob/163a2abc047a75304b7c27305bc2231b4ed58f6d/self-core-impl/src/main/java/com/selfxdsd/core/GithubIssue.java#L44-L46

"Labels API: should be able to list and add labels for Provider resources (Repo, Issue). Labels will be used mainly for an Issue to get its estimation.".

It was created by cristianpela on 2020-07-22T11:33:14Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
