### ISSUE TITLE
Code formatting rules

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-core#762]
Are there any formatting rules that I can use to configure my editor (IDEA)?
Because I get many changes when I use automatique formatting.
Or I'm missing something?

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-15T20:35:49.576025``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@fellahi-ali I have no formatting file, unfortunately.

The rules are, in essence:

- 4-space indentation, no TABs
- lines no longer than 80 chars
- open/close brackets on new row, similar to the rule used by 0crat

**Comment by fellahi-ali** [comment]
@amihaiemil thanks, that would help
> And dont use IDE autoformat, it will most likely break everything :D
I'm used to type CTRL+ALT+L (auto formatting shortcut) unconsciously just like CTRL+S but I will try to unlearn it :(

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
