### ISSUE TITLE
Bug in GitlabIssues.getById(); GithubIssue.java is used instead of GitlabIssue.java

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-core#778]
@amihaiemil @criske There is bug in the implementation of `GitlabIssues.getById()` method, where `GithubIssue` is used instead of `GitlabIssue` instance. 

https://github.com/self-xdsd/self-core/blob/6852fc54eec416de08f733482edee6942a30ec81/self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssues.java#L113-L119

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-18T18:55:50.570948``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

**Comment by amihaiemil** [comment]
@criske I missed that at CR, sorry :D 

Even if the JSON of a Gitlab Issue is the same as for Github, we still need a GitlabIssue implementation, in order to stay consistent :D 

Maybe later we can extract a base class if necessary.

**Comment by criske** [comment]
> @criske I missed that at CR, sorry :D
> 
> 

@amihaiemil nah this was entirely my fault, this test was incomplete. 
https://github.com/self-xdsd/self-core/blob/6852fc54eec416de08f733482edee6942a30ec81/self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssuesTestCase.java#L55
If json response would've had `iid`, I've would be able to notice it.

@fellahi-ali thank you for catching it, I'll fix it asap :D

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
