### ISSUE TITLE
Review Messages

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#781]
Now that we have the documentation set up, let's review the messages the PM gives and add documentation links where appropriate.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-21T11:01:13.420508``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it partially and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.
