### ISSUE TITLE
InMemoryContracts.java:40-42: When Storage API has...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#79]
The puzzle `74-6fc04657` from #74 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/5f34b2bfe05f1f432571cfe39ff514a7555dc552/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java#L40-L42

The puzzle was created by cristianpela on 23-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by amihaiemil** [comment]
waiting for #84

**Comment by 0pdd** [comment]
The puzzle `74-6fc04657` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
