### ISSUE TITLE
GitlabCommit.java: finish the implementation of ... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#809]
The puzzle ``806-314f817b`` originating from #806 has to be resolved:

https://github.com/self-xdsd/self-core/blob/a8e44ffea49af91b9ba7bcc6e00d6a65451c5743/self-core-impl/src/main/java/com/selfxdsd/core/GitlabCommit.java#L39-L41

"finish the implementation of this class and write the appropriate tests. Check GithubCommit for inspirations, and the Gitlab api doc at https://docs.gitlab.com/ee/api/commits.html#get-a-single-commit.".

It was created by @amihaiemil on 2020-12-19T17:51:40Z. Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2020-12-29T19:53:08.875311``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@andreoss Don't forget to close this ticket before the deadline (2020-12-29T19:53:08). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@andreoss Looks like you've missed the task deadline (2020-12-29T19:53:08). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-08T19:57:08.622629``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike quit

**Comment by charlesmike** [comment]
> @charlesmike quit

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-08T20:18:05.774677``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
paid with transaction id 8NA2897845818554P

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
