### ISSUE TITLE
InMemoryProjectsTestCase.java:23-25: Continue writing...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#82]
The puzzle `39-dcb763b9` from #39 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/dcf245af1c4e1f526fe84c9064b0cba9d6cbfd0b/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectsTestCase.java#L23-L25

The puzzle was created by HoreaPetrila on 23-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by HoreaPetrila** [comment]
Can work on the remaining tests in InMemoryProjectManagers

**Comment by 0pdd** [comment]
The puzzle `39-dcb763b9` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
paid with transaction id 14T67214XV3416901
