### ISSUE TITLE
GitlabIssueCommentsTestCase.java: Add tests for GilabIssueComme... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#823]
The puzzle ``726-7b8291f9`` originating from #726 has to be resolved:

https://github.com/self-xdsd/self-core/blob/70f130c80eeda3d5dd5f82e56565ee8f8c4634b9/self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java#L40-L41

"Add tests for GilabIssueComments.post(...) and GitlabIssueComments.received(...).".

It was created by @andreoss on 2020-12-22T23:29:45Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-02T12:28:02.593621``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike quit

**Comment by charlesmike** [comment]
> @charlesmike quit

@amihaiemil ok, I'll find someone else to take care of it.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-05T12:54:04.372645``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by amihaiemil** [comment]
paid with transaction id 2HP480764L5436119
