### ISSUE TITLE
InMemoryProjectManagers.java:38-39: Add ProjectManager...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#83]
The puzzle `68-34d53a58` from #68 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/9bd0ea7b1986a12e0e8ef4cc5037829cf26d819b/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java#L38-L39

The puzzle was created by Bogdan Adrian on 24-May-20. 

Estimate: 20 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
i'll take it

**Comment by 0pdd** [comment]
The puzzle `68-34d53a58` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
paid with transaction id: 19J074570N612361L
