### ISSUE TITLE
Missing test for GitlabIssueComments.iterator()

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-core#835]
While working on #823, I noticed that `GitlabIssueComments.iterator()` is not tested for the happy path, or am I missing something?

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-06T00:30:07.494692``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by criske** [comment]
@fellahi-ali It looks like that test is covered by `receivesCommentFromJson` https://github.com/self-xdsd/self-core/blob/f90cedad107686714e159464bd42c8c0d663b916/self-core-impl/src/test/java/com/selfxdsd/core/GitlabIssueCommentsTestCase.java#L68

**Comment by amihaiemil** [comment]
@fellahi-ali @criske right, that test covers it. I think it's enough :D

**Comment by amihaiemil** [comment]
paid with transaction id 15B17051UL637764W

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by fellahi-ali** [comment]
@amihaiemil @criske sorry, my bad, I haven't noticed nor understood that test :(

**Comment by amihaiemil** [comment]
@fellahi-ali no worries :D
