### ISSUE TITLE
Can't use GitlabComment to represent a Commit comment because of API inconsistency  

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-core#838]
To fix #809 I have to implement `GitlabCommitComments` `post()` and `received()` which should return a `Comment` object but unfortunately the current implementation of  `GitlabComment` can only represent an _issue_ comment but not a _commit_ comment because Gitlab's API represent those comments differently, where the _issue_ comment uses `body` attribute and the _commit_ comment uses `note` attribute for the body of the comment (see examples below).
* Example of _issue_ comment:
```json
{
    "id": 305,
    "body": "Text of the comment\r\n",
    "attachment": null,
    "author": {
      "id": 1,
      "username": "pipin",
      "email": "admin@example.com",
      "name": "Pip",
      "state": "active",
      "created_at": "2013-09-30T13:46:01Z"
    },
    "created_at": "2013-10-02T09:56:03Z",
    "updated_at": "2013-10-02T09:56:03Z",
    "system": true,
    "noteable_id": 121,
    "noteable_type": "Issue",
    "noteable_iid": 121,
    "resolvable": false,
    "confidential": true
  }
```
* Example of _commit_ comment: 
```json
{
   "author" : {
      "web_url" : "https://gitlab.example.com/thedude",
      "avatar_url" : "https://gitlab.example.com/uploads/user/avatar/28/The-Big-Lebowski-400-400.png",
      "username" : "thedude",
      "state" : "active",
      "name" : "Jeff Lebowski",
      "id" : 28
   },
   "created_at" : "2016-01-19T09:44:55.600Z",
   "line_type" : "new",
   "path" : "dudeism.md",
   "line" : 11,
   "note" : "Nice picture man!"
}
``` 
My suggestion is to rename `GitlabComment` to `GitlabIssueComment` and add `GitlabCommitComment` to represent the two cases.
WDYT @amihaiemil?

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-09T12:30:06.514535``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@fellahi-ali right, from what I see, the differences are quite big. So let's go with your suggestion.

**Comment by fellahi-ali** [comment]
@amihaiemil I run into another issue while trying to implement `GitlabCommitComment`
Unlike Github's **commit** comments  and the Gitlab's **issue** comments, there is no `id` attribute in the Gitlab **commit** comment JSON response (check the example above or see: https://docs.gitlab.com/ee/api/commits.html#get-the-comments-of-a-commit)
And so I don't know how to implement `commentId()` method?
The only thing that could represent the `id` is a combination of `"path"` &  `"line"` attributes, but I'm not sure if this could work for us and how to implement it.

**Comment by amihaiemil** [comment]
@fellahi-ali strange that Gitlab doesnt provide the ID... you can just make it throw ``UnsupportedOperationException`` -- I don't think we even use this ID anywhere, to be honest.

So just:

```java
@Override
public String commitId() {
    throw new UnsupportedOperationException("GitLab Commit Comment has no ID");
}
```

**Comment by fellahi-ali** [comment]
@amihaiemil I was experimenting with the API and noticed that there is a `/discussions` endpoint which strangely returns the created comments with their `id`s, but unfortunately nested in a `discussion` object and inside `notes` array!!! 
The response of `GET https://gitlab.com/api/v4/projects/23395047/repository/commits/231fb9aed0c772abdb8ae44ad1c8a55fcccbedd7/discussions`

The first object is created using  the `/comments` endpoint and the second is created using the `/discussions` end point.

```json
[
    {
        "id": "d89e4eca84a93cc1d143127d48f24c8bdd56d99e",
        "individual_note": true,
        "notes": [
            {
                "id": 476354628,
                "type": null,
                "body": "test comment",
                "attachment": null,
                "author": {
                    "id": 4507429,
                    "name": "Ali FELLAHI",
                    "username": "fellahi.ali",
                    "state": "active",
                    "avatar_url": "https://secure.gravatar.com/avatar/3c87b8279d4cdd7860f00cf107f27147?s=80&d=identicon",
                    "web_url": "https://gitlab.com/fellahi.ali"
                },
                "created_at": "2020-12-31T10:19:15.068Z",
                "updated_at": "2020-12-31T10:19:15.068Z",
                "system": false,
                "noteable_id": null,
                "noteable_type": "Commit",
                "resolvable": false,
                "confidential": false,
                "noteable_iid": null,
                "commands_changes": {}
            }
        ]
    },
    {
        "id": "10a4c7256b32ee18a51f012d4cc690b21e79ec37",
        "individual_note": false,
        "notes": [
            {
                "id": 476357250,
                "type": "DiscussionNote",
                "body": "test discussion",
                "attachment": null,
                "author": {
                    "id": 4507429,
                    "name": "Ali FELLAHI",
                    "username": "fellahi.ali",
                    "state": "active",
                    "avatar_url": "https://secure.gravatar.com/avatar/3c87b8279d4cdd7860f00cf107f27147?s=80&d=identicon",
                    "web_url": "https://gitlab.com/fellahi.ali"
                },
                "created_at": "2020-12-31T10:28:02.630Z",
                "updated_at": "2020-12-31T10:29:00.236Z",
                "system": false,
                "noteable_id": null,
                "noteable_type": "Commit",
                "resolvable": false,
                "confidential": false,
                "noteable_iid": null,
                "commands_changes": {}
            }
        ]
    }
]
```

**Comment by amihaiemil** [comment]
@fellahi-ali We don't need that now.

Actually, when it comes to Commit Comments, we are not so interested in the existing comments, we don't read them (at the moment we implement GitlabCommitComment just to have a consistent architecture).

Fow now we use Commit Comments just to post comments about newly opened Issues and closed Issues (self-todos). So it's ok if you just make that method throw UnsupportedOperationException.

**Comment by amihaiemil** [comment]
paid with transaction id 4NH176398B840772G

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
