### ISSUE TITLE
GitlabComment.author() should return author.username

### ISSUE THREAD

**Issue by fellahi-ali** [self-xdsd/self-core#839]
@amihaiemil Shouldn't `author()` return `author.username` instead of `author.name`?

https://github.com/self-xdsd/self-core/blob/17fa56f274d3b676988ac069bf7432e512c2f600/self-core-impl/src/main/java/com/selfxdsd/core/GitlabComment.java#L37-L39

```json
"author": {
      "id": 1,
      "username": "pipin",
      "email": "admin@example.com",
      "name": "Pip",
      "state": "active",
      "created_at": "2013-09-30T13:46:01Z"
}
```

**Comment by charlesmike** [comment]
@fellahi-ali thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@fellahi-ali I think so, yes :D

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-09T12:48:06.572683``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
15min

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
