### ISSUE TITLE
Make Collaborators Iterable of Collaborator

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#852]
In the case of Gitlab, we need to be able to iterate over the collaborators of a Repo. Let's make the interface Collaborators be an Iterable of Collaborator: https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project

The Collaborator interface needs to have the methods: id(), username(), name() and json().

For class GithubCollaborators, we can make the iterator method throw UnsupportedOperationException, we are not interested in it at the moment.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-13T13:04:52.926644``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
paid with transaction id 6L15691413685251M

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
