### ISSUE TITLE
Charge Contributor VAT

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#853]
Self XDSD has to pay VAT (19%) for the commission it takes. Since the commission is taken from the Contributor ([docs](https://docs.self-xdsd.com/wallets.html#invoicing)) we also have to charge them the VAT as follows:

If Contributor is from Romania => charge VAT always

If Contributor is from other countries of the EU => charge VAT **unless** the Contributor provides their company details with a valid VAT number.

If Contributor is from outside the EU => **do not** charge VAT.

For a transaction of 108 EUR (100 EUR to the Contributor, 8 EUR Self's commission) with VAT charge, the Contributor receives 98.48 EUR (100 - 19% * 8).

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-14T17:21:52.823059``.

Estimation here is ``120 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
