### ISSUE TITLE
VAT Should Not Be Part Of Invoice

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#858]
Reversing modifications introduced in PR #857 for Issue #855. 
The contributorVat will be sent separately (as a second parameter) to method registerAsPaid(...).

For each invoice registered as paid (with a real wallet), we should create a SelfInvoice (invoice from Self to Contributor) in a new table (1-1 relationship between Invoice and SelfInvoice, starting from SelfInvoice).

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-16T15:06:48.491289``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.
