### ISSUE TITLE
GitlabCollaborators.java: Write unit tests for the iter... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#859]
The puzzle ``852-6bdc03a5`` originating from #852 has to be resolved:

https://github.com/self-xdsd/self-core/blob/54f791fc0c805ff7e0de83fc915c559114a6cb94/self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java#L22-L23

"Write unit tests for the iterator() happy and unhappy paths.".

It was created by @fellahi-ali on 2021-01-05T21:55:36Z. Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-16T16:48:49.260067``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
paid with transaction id 9D706617GJ118602P

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
