### ISSUE TITLE
InMemoryProjectManagers.java:38-41: Add to the ability...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#86]
The puzzle `69-62299523` from #69 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/08078cf10d7cf9ac216065f1ecc2bb8dbfeb579b/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryProjectManagers.java#L38-L41

The puzzle was created by cristianpela on 24-May-20. 

Estimate: 20 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by criske** [comment]
I'll continue to implement this

**Comment by amihaiemil** [comment]
paid with transaction id 7UP051724B735853W

**Comment by 0pdd** [comment]
The puzzle `69-62299523` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
