### ISSUE TITLE
Add Invoice Number

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#864]
At the moment we use the incremental DB id for an Invoices ID always. This means Invoice 1 can go to Contributor A, Invoice 2 and 3 to Contributor B and then Invoice 4 to Contributor A. This will create chaos in the Contributor's bookings because the the numbering of their invoices will not have any rules.

As a solution, each Contributor should have their own counter for their Invoices. For that, we need the field Invoice.number.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-17T14:59:40.264108``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
turns out there are too many complications for this to be implemented. As such, the Contributor will have to assign their company's numbers/series manually for each Invoice, before putting it into the books.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
