### ISSUE TITLE
InMemoryWallets.java: As soon as we have the Stripe... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#868]
The puzzle ``500349511`` originating from #499 has to be resolved:

https://github.com/self-xdsd/self-core/blob/05eba6753dfb6854543ed1809b96647b863399e1/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryWallets.java#L41-L43

"As soon as we have the Stripe wallet implemented, modify the register(...) method here to take it into account, according to the given type (at the moment, it always registers the Missing wallet).".

Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-18T10:39:33.462733``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
