### ISSUE TITLE
GitlabCollaborators.java: Write unit tests for the iter... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#873]
The puzzle ``-303497025`` originating from #852 has to be resolved:

https://github.com/self-xdsd/self-core/blob/05eba6753dfb6854543ed1809b96647b863399e1/self-core-impl/src/main/java/com/selfxdsd/core/GitlabCollaborators.java#L22-L23

"Write unit tests for the iterator() happy and unhappy paths.".

Estimation is ``30 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@charlesmike deregister

**Comment by charlesmike** [comment]
> @charlesmike deregister

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.
