### ISSUE TITLE
Invoices.java: Implement the PlatformInvoice... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#886]
The puzzle ``1382593047`` originating from #867 has to be resolved:

https://github.com/self-xdsd/self-core/blob/9c0ab39d8ddc71cdb8b5f54d81f2910bc52b12de/self-api/src/main/java/com/selfxdsd/api/Invoices.java#L13-L14

"Implement the PlatformInvoice. This will represent the invoices emitted by Self XDSD to the Contributors.".

Estimation is ``90 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-18T13:39:13.533743``.

Estimation here is ``90 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@criske FYI, we will have a new entity. 

Initially, I wanted to generate the platform's invoice from the Invoice, but it's too complicated. Besides, we want to still keep our platform invoices even if the Contributor deletes their Contract (together with the Invoices).

**Comment by criske** [comment]
@amihaiemil Gotacha. So Contributor will have access only to PlatformInvoices?

**Comment by amihaiemil** [comment]
@criske No, Contributor will have access both to Invoices  (his invoices to the Project) and to PlatformInvoices (which are the invoices emitted by Self to him). 

The Project/PO will never see the PlatformInvoices, because it's not their business.

We will also have to implement a page in self-web where the admins will see the platform invoices (we will need to download them and send then to accounting).

**Comment by criske** [comment]
@amihaiemil Makes sense. One question, since Contributor has access to both, the Project Invoice will have 100EUR or 108EUR amount? Cause at the moment, if I'm correct, it includes the Platform commission.

**Comment by amihaiemil** [comment]
@criske The PolatformInvoice will have 8 EUR on it. Have a look at the invoicing diagram: 

The Contributor emits an Invoice to the Project with 108 EUR (his 100 EUR + 8 EUR Self commission). However, he actually receives only 100 EUR. 

Therefore, we Self have to give then an invoice (the PlatformInvoice) for the 8 EUR we retained. 

The Contributor will add these 2 invoices in their accounting: the Invoice will say that he earned 108 EUR, and the PlatformInvoice will say that he paid 8 EUR => he earned 100 EUR.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
