### ISSUE TITLE
Invoice: update toPdf to accept an OutputStream instead of returning File.

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#895]
https://github.com/self-xdsd/self-core/blob/045204a02fb5d0e379e27fd75273814ff12c0837/self-api/src/main/java/com/selfxdsd/api/Invoice.java#L112
As mentioned [here](https://github.com/self-xdsd/self-web/issues/314), we should update the `Invoice#toPdf` to accept an `OutputStream` as parameter instead of returning `File`. By writting directly into the stream, this will make the whole process more efficient and prevent possible concurrency issues when the same pdf files are generated in the same time.

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-20T12:16:13.088614``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
paid with transaction id 6KD591077T291343A

**Comment by charlesmike** [comment]
@andreoss thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
