### ISSUE TITLE
Implement "GitlabIssue#comments()"

### ISSUE THREAD

**Issue by criske** [self-xdsd/self-core#909]
Implement `GitlabIssue#comments()` by following the Github model.
We already have `GitlabIssueComments`. It only needs to be hooked up.

https://github.com/self-xdsd/self-core/blob/b48ba0cf2e568c5295d058a8b2c32627e61fc97a/self-core-impl/src/main/java/com/selfxdsd/core/GitlabIssue.java#L229-L232

**Comment by charlesmike** [comment]
@criske thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-01-24T13:26:15.424481``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
