### ISSUE TITLE
Add method Issues :: Repo.pullRequests()

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#932]
In the case of GitLab, we need to differentiate between Issues and Merge Requests (Issues URI is /issues, MR URI is /merge_requests). 

Let's start by adding the method ``Issues :: Repo.pullRequests()``.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-05T11:59:26.226730``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske FYI, we have a problem: Github does not differentiate between Issues and PRs in their API (they have the same URIs and the same incremental ID). On the other hand, GitLab differentiates between them. 

The result is: my ``add`` command on MR 1: https://gitlab.com/self-xdsd/self-rest/-/merge_requests/1#note_493975437 resulted in action upon Issue 1: https://gitlab.com/self-xdsd/self-rest/-/issues/1#note_493975621

**Comment by criske** [comment]
@amihaiemil This will help fixing the bug  in self-pm, right? Cause right now, looks like  the self-pm `GitlabWebhookEvent` is searching MR as a normal Issue by id instead of finding MR like `https://gitlab.com/owner/name/-/merge_requests/id`.

**Comment by amihaiemil** [comment]
@criske yes, exactly.

And it will also be used inside Task.issue(), based on the isPullRequest flag.

**Comment by criske** [comment]
> And it will also be used inside Task.issue(), based on the isPullRequest flag.

@amihaiemil Yep, now that you mentioned it, I think I've forgot to update the "equals/hashCode" with the pr flag  in my PR https://github.com/self-xdsd/self-core/pull/936

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
