### ISSUE TITLE
Implement class TaskIssue (implements Issue)

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#938]
We need to have an Issue implementation based on Task. 

Later, we will use ``E-Tags`` to read Issues from Github/GitLab API and the response will be 304 NOT MODIFIED (if there were no modifications) with an empty body. This will help us because these calls will not cound in the Rate Limit. 

For this scenario, we need class TaskIssue, to return the Issue based on the existing Task.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-05T16:05:29.663467``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.
