### ISSUE TITLE
Contract.java:32-34: Implement and test StoredContract,...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#94]
The puzzle `79-580e807d` from #79 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/7380b67b3c6869df69708cd5b38d83a860575992/self-api/src/main/java/com/selfxdsd/api/Contract.java#L32-L34

The puzzle was created by @amihaiemil on 24-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by HoreaPetrila** [comment]
I'm giving it a try

**Comment by 0pdd** [comment]
The puzzle `79-580e807d` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@HoreaPetrila paid with transaction id 9CT71976J8643291S
