### ISSUE TITLE
Create the Admin interface

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#946]
At the moment the core exposes the ``PlatformInvoices`` (method Self.platformInvoices()). 
This means, the PlatformInvoices can be accessed without any actual login.

Let's add interface Admin:

```java
/**
 * Admin user in Self XDSD.
 */
public interface Admin {
    PlatformInvoices platformInvoices();
}
```

We also have to add the method ``Admin :: User.asAdmin()``. 

Then, remove the method ``Self.platformInvoices()``.

As effect, in order to access the platform invocies, login will be required:

```java
Self.login().asAdmin().platformInvoices();
```

In this task, implement just these changes and write todos to continue with implementing method User.asAdmin() and a class which implements interface Admin.

**Comment by charlesmike** [comment]
@amihaiemil thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by amihaiemil** [comment]
@nmonokov please accept the invitation I sent you, to join the Self XDSD organization. Otherwise, I won't be able to assign tasks to you. 

I want to assign this ticket to you :D

**Comment by amihaiemil** [comment]
@charlesmike remove

**Comment by charlesmike** [comment]
> @charlesmike remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by nmonokov** [comment]
@amihaiemil haven't I done it already? Can you help me understand where can i accept this invite if it's not done yet?

**Comment by amihaiemil** [comment]
@nmonokov nope, you haven't accepted it. It's an Invitation in Github to join the self-xdsd organization

You should have an e-mail from Github with this invitation, or a Notification in Github UI :D 

<img width="1281" alt="Screenshot 2021-01-30 at 17 47 42" src="https://user-images.githubusercontent.com/6305156/106360859-8f0e0d00-6323-11eb-95e3-5efca47b3c30.png">

**Comment by nmonokov** [comment]
@amihaiemil For some reason i don't have any invitations. I was a participant in one organization. I've left it now. No email to join self-xdsd and no notifications. Maybe try send another invitation? Maybe the it happened due to my participation in the previous one and github has some weird limit for that?
![image](https://user-images.githubusercontent.com/10772631/106370633-d53b8e80-636c-11eb-986f-79f381203fb5.png)

**Comment by nmonokov** [comment]
done it

**Comment by amihaiemil** [comment]
@charlesmike add

**Comment by charlesmike** [comment]
> @charlesmike add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by charlesmike** [comment]
@nmonokov this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-10T09:57:50.114349``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by amihaiemil** [comment]
@nmonokov please send me your PayPal address!

**Comment by nmonokov** [comment]
@amihaiemil unfortunately in Ukraine we can't receive PayPal payments. But I have a payoneer account. If this works for you :).

**Comment by amihaiemil** [comment]
@nmonokov I'll have a look into Payoneer :D

**Comment by charlesmike** [comment]
@nmonokov thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).

**Comment by amihaiemil** [comment]
paid with transaction id 40U698504T452040N
