### ISSUE TITLE
Implement ApiTokens

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#947]
A User will have multiple api tokens which they will use to authenticate in Self's Restful API.

We need the method ``ApiTokens :: User.apiTokens()``.

Interface ApiTokens will be an iterable of ApiToken.

An ApiToken has a name, value and expiration date.

Interface ApiTokens will also have the method ``ApiTokens :: ofUser(User)``.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-08T21:41:43.733429``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by charlesmike** [comment]
@andreoss Don't forget to close this ticket before the deadline (2021-02-08T21:41:43). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 3J409383AT4419433

**Comment by charlesmike** [comment]
@andreoss thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
