### ISSUE TITLE
InMemoryContributors.java:40-42: Write some unit tests...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#95]
The puzzle `79-282aa471` from #79 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/7380b67b3c6869df69708cd5b38d83a860575992/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContributors.java#L40-L42

The puzzle was created by @amihaiemil on 24-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by HoreaPetrila** [comment]
I'll do it

**Comment by 0pdd** [comment]
The puzzle `79-282aa471` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil

**Comment by amihaiemil** [comment]
@HoreaPetrila paid with transaction id 6RP99907P46129158
