### ISSUE TITLE
Admin.java: Implement and test Admin user... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#959]
The puzzle ``1417992982`` originating from #946 has to be resolved:

https://github.com/self-xdsd/self-core/blob/975458945f8aad50041a2d90ce21329a9c164b2d/self-api/src/main/java/com/selfxdsd/api/Admin.java#L30-L30

"Implement and test Admin user class.".

Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
@nmonokov Wanna take this up? It shouldn't be very hard : D

**Comment by amihaiemil** [comment]
@nmonokov actually, I'm looking over it now. I want to have a look first, it requires quite a few changes.:D

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-10T13:57:53.691376``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by nmonokov** [comment]
@amihaiemil that was fast :D Any issue available, I'm ready to dig in.

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@amihaiemil thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
