### ISSUE TITLE
InMemoryContracts.java:41-43: Implement and test Project...

### ISSUE THREAD

**Issue by 0pdd** [self-xdsd/self-core#96]
The puzzle `79-2e30e1fe` from #79 has to be resolved: 

https://github.com/self-xdsd/self-core/blob/7380b67b3c6869df69708cd5b38d83a860575992/self-core-impl/src/test/java/com/selfxdsd/core/mock/InMemoryContracts.java#L41-L43

The puzzle was created by @amihaiemil on 24-May-20. 

Estimate: 30 minutes,  role: DEV. 

If you have any technical questions, don't ask me, submit new tickets instead. The task will be \"done\" when the problem is fixed and the text of the puzzle is _removed_ from the source code. Here is more about [PDD](http://www.yegor256.com/2009/03/04/pdd.html) and [about me](http://www.yegor256.com/2017/04/05/pdd-in-action.html).

**Comment by 0pdd** [comment]
@amihaiemil please pay attention to this new issue.

**Comment by BogdanAdrian11** [comment]
I'll take this.

**Comment by amihaiemil** [comment]
@BogdanAdrian11 paid with transaction id 8527787064150430H

**Comment by 0pdd** [comment]
The puzzle `79-2e30e1fe` has disappeared from the source code, that's why I closed this issue. //cc @amihaiemil
