### ISSUE TITLE
ApiTokens.java: Implement method ApiTokens.re... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#972]
The puzzle ``-52669715`` originating from #951 has to be resolved:

https://github.com/self-xdsd/self-core/blob/afd7a39ffb19cc3ccc3a3e066c8f1e9a85678e14/self-api/src/main/java/com/selfxdsd/api/ApiTokens.java#L31-L34

"Implement method ApiTokens.register(name, token, expiration,User), which should register a new token. Also implement method User.register(name, token expiration) which should forward the call to the method in ApiTokens with this User.".

The puzzle was created by @amihaiemil at ``2021-02-05 10:51:55 +0200``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@andreoss this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-15T11:03:03.592052``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@andreoss Don't forget to close this ticket before the deadline (2021-02-15T11:03:03). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
paid with transaction id 8EE19093LC0792313

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@andreoss thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
