### ISSUE TITLE
ApiTokens.java: Implement and test method Api... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#973]
The puzzle ``-371424315`` originating from #951 has to be resolved:

https://github.com/self-xdsd/self-core/blob/afd7a39ffb19cc3ccc3a3e066c8f1e9a85678e14/self-api/src/main/java/com/selfxdsd/api/ApiTokens.java#L35-L36

"Implement and test method ApiTokens.remove(token) which should remove the token if it exists.".

The puzzle was created by @amihaiemil at ``2021-02-05 10:51:55 +0200``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by amihaiemil** [comment]
To be more clear: We need method ApiTokens.remove(ApiToken) and method ApiToken.remove(). Inside StoredApiToken, the method remove will look like:


```java
@Override
public boolean remove() {
    return this.storage.apiTokens().remove(this);
}
```

**Comment by charlesmike** [comment]
@criske this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-15T11:03:07.752263``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by charlesmike** [comment]
@criske thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
