### ISSUE TITLE
Bitbucket.java: Start scaffolding BitbucketOr... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#978]
The puzzle ``304993195`` originating from #943 has to be resolved:

https://github.com/self-xdsd/self-core/blob/3ed3f652b05ddb000e9e40799480488e306519ff/self-core-impl/src/main/java/com/selfxdsd/core/Bitbucket.java#L46-L49

"Start scaffolding BitbucketOrganizations using the other providers as model. Documentation reference: https://developer.atlassian.com/bitbucket/api/2/reference/resource/teams".

The puzzle was created by @cristianpela at ``2021-02-06 11:06:34 +0200``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@nmonokov this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-16T17:13:12.364535``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@nmonokov Don't forget to close this ticket before the deadline (2021-02-16T17:13:12). You are past the first half of the allowed period.

**Comment by nmonokov** [comment]
Sure!

**Comment by charlesmike** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by amihaiemil** [comment]
paid with transaction id 4T509391N90321259

**Comment by charlesmike** [comment]
@nmonokov thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
