### ISSUE TITLE
Let's Start Implementing Payments

### ISSUE THREAD

**Issue by amihaiemil** [self-xdsd/self-core#979]
Payments will be an Iterable of Payment and will belong to an Invoice.

A Stripe payment of an Invoice may fail for some reason and we should register it. An Invoice will have one or more payments and it will be considered paid when the first successful Payment occurs.

A Payment should have a transactionId, timestamp, value, status (FAILED, SUCCESSFUL) and reason ("authentication required", "not enough funds" etc).

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-19T19:49:05.351252``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil please keep in mind that manual assignment of tickets is a bad practice and it is discouraged. Next time, please let me elect the assignee.

**Comment by amihaiemil** [comment]
@criske FYI

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-02-19T19:49:05). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2021-02-19T19:49:05). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-01T19:57:55.849239``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by fellahi-ali** [comment]
@amihaiemil In the current API design, the `Invoice` has `paymentTime()`, `transactionId()` & `totalAmount()`  which are basically the attributes of the new proposed `Payment` API in case of a successful payment. (if I'm getting it right).
Now, my question is, in the scope of this task, should we refactor the `Invoice` to remove the `Payment` related info?
I have also another suggestion, as we already have the SUCCESSFUL `Payment` registered with the paid `Invoice`, wouldn't be more clean to only add an API to register FAILED `Payment`s.
I'm not sure about all this, maybe I'm just over thinking/designing it, any guidance would be very appreciated :)

**Comment by amihaiemil** [comment]
@fellahi-ali The Invoice is the last thing to be modified, after we have the Payments in place :D 

All the payments of an Invoice (failed and the last, successful one) will be in the payments table - that's the correct way to do it, I think. 

Just start with the Payments iterable of Payment. Interface Payments should look like this:

```java
public interface Payments extends Iterable<Payment> {
     Payment register(Payment);

     Payments ofInvoice(Invoice);
}
```

The Payment interface should have the accessor methods as described in this ticket and also the method ``Invoice :: invoice()``.

Also add the payments() method to the Storage interface. 
I think if you start with these interfaces and also start implementing StoredPayment should be enough for this task :D 

Finally, write a TODO to modify the Wallet.pay(...) method to return the Payment. We will have a Wallet decorator which will encapsulate the inital wallet, get the Payment and register in the DB. 

Only afterwards we will modify the Invoice object.

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-03-01T19:57:55). You are past the first half of the allowed period.

**Comment by fellahi-ali** [comment]
@amihaiemil could you please re-assign me this task, because I already started to work on it, but unfortunately didn't managed to finish it in time :(

**Comment by amihaiemil** [comment]
@fellahi-ali sure, no prob

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-11T09:17:17.747014``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by fellahi-ali** [comment]
> Finally, write a TODO to modify the Wallet.pay(...) method to return the Payment. We will have a Wallet decorator which will encapsulate the inital wallet, get the Payment and register in the DB.

@amihaiemil I don't think we should modify Wallet.pay() return type to return a Payment, because we can just use the invoice.payments() to register the new payment, WDYT?

**Comment by amihaiemil** [comment]
@fellahi-ali I would like to modify Wallet.pay(...) to return the Payment for a few reasons:

1. It seems logical: when you pay something, you create a Payment, right? At the moment this method returns the modified Wallet, which doesn't really make sense to me. 

2. Maybe we will want to make something with this Payment information later (for instance send it via e-mail to the Customer). Actually, we will need this Payment in the /payInvoice endpoint of self-web: when the user clicks the "pay invoice" icon, they should receive as response the Payment.

3. I'm not sure yet if StripeWallet and FakeWallet will also register the Payment in the DB. Maybe it's better if they just produce it from ``pay(...)`` and we save it using a decorator. You see, at the moment, there are many exceptional cases inside StripeWallet.pay(...) -- I'm not yet sure what to do with those. 

Makes sense? :D

**Comment by fellahi-ali** [comment]
> Makes sense? :D

Indeed, it makes lot of sense :) I thought we only need to register the Payment in the DB.

**Comment by zoeself** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
