### ISSUE TITLE
BitbucketOrganizationRepos.java: Continue implementing this cl... 

### ISSUE THREAD

**Issue by charlesmike** [self-xdsd/self-core#984]
The puzzle ``1962974179`` originating from #978 has to be resolved:

https://github.com/self-xdsd/self-core/blob/504a7a5402c38e0c9fd6d1a6d290d93be1c144b2/self-core-impl/src/main/java/com/selfxdsd/core/BitbucketOrganizationRepos.java#L19-L19

"Continue implementing this class and writing tests for it.".

The puzzle was created by @amihaiemil at ``2021-02-12 12:26:26 +0200``. 
Estimation is ``60 minutes``.
If you have any technical questions, don't ask me, I won't be able to help. Open new issues instead.

**Comment by charlesmike** [comment]
@amihaiemil this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-02-22T12:30:24.639826``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@amihaiemil Don't forget to close this ticket before the deadline (2021-02-22T12:30:24). You are past the first half of the allowed period.

**Comment by charlesmike** [comment]
@amihaiemil Looks like you've missed the task deadline (2021-02-22T12:30:24). You are now resigned from this task.

Please stop working on it, you will not be paid. I will assign it to someone else soon.

**Comment by charlesmike** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-04T16:37:35.743333``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by charlesmike** [comment]
@fellahi-ali Don't forget to close this ticket before the deadline (2021-03-04T16:37:35). You are past the first half of the allowed period.

**Comment by amihaiemil** [comment]
@fellahi-ali Same here, just a sketch is fine and a todo to continue.

**Comment by fellahi-ali** [comment]
@amihaiemil you know, I didn't see this task until now :( and its not listed in my contributor tab

**Comment by amihaiemil** [comment]
@fellahi-ali i forgot to ask Zoe to put it into scope, sorry :D 

This task has been opened by charlesmike from Test, but now we use Self XDSD prod.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
> @zoeself add

@amihaiemil I've just registered this ticket as a task and will assign it to someone soon. Thanks!

**Comment by zoeself** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-18T11:57:17.739598``.

Estimation here is ``60 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by fellahi-ali** [comment]
> @fellahi-ali Same here, just a sketch is fine and a todo to continue.

@amihaiemil I think it's fair to set the estimate for this task 30min as it will not need actual implementation.

**Comment by amihaiemil** [comment]
@zoeself remove

**Comment by zoeself** [comment]
> @zoeself remove

@amihaiemil ok, I've removed this task from scope. I'm not managing it anymore.

**Comment by amihaiemil** [comment]
@zoeself add

**Comment by zoeself** [comment]
@fellahi-ali this is your task now, please go ahead. Deadline (when this ticket should be closed) is ``2021-03-18T14:37:17.726102``.

Estimation here is ``30 minutes``, that's how much you will be paid.

Remember, you don't have to solve everything in this ticket - you can solve it [partially](https://docs.self-xdsd.com/microtasking.html) and leave ``todo`` markers in the code, which will become future tasks.

If you have any questions don't ask me, I'm not a technical person. Open new tickets instead.

If you don't have time or simply don't want to work on this, you can always [resign](https://docs.self-xdsd.com/projectmanager.html#commands).

**Comment by zoeself** [comment]
Puzzle disappeared from the code, that's why I closed this ticket.

**Comment by zoeself** [comment]
@fellahi-ali thank you for resolving this ticket. I've just added it to your active invoice. You can always check all your invoices and more on the [Contributor Dashboard](https://self-xdsd.com).
